;;;; Ferramentas visuais do jogo. A engine continua integralmente em antigonus.lisp.
(in-package #:asterion-assembly)

(defvar *predio-seletor-sinal* nil)
(defvar *campo-seletor-sinal* nil)
(defvar *opcoes-seletor-sinal* #())
(defvar *filtro-seletor-sinal* :all)
(defvar *indice-seletor-sinal* 0)
(defvar *pausa-antes-seletor* nil)
(defparameter *filtros-seletor-sinal* #(:all :item :fluid :virtual :special))

(defun campo-sinal-circuito (predio pagina linha)
  (let ((condicao (circuit-device-config-condition (configuracao-circuito-padrao predio))))
    (if (plusp pagina)
        (when (eq (first (nth linha (campos-avancados-circuito predio))) :right) :right)
        (case linha
          (1 (cond ((eq (building-kind predio) :circuit-sensor) :output)
                   (condicao :left) (t :input)))
          (4 (if (member (building-kind predio) '(:arithmetic-combinator :decider-combinator))
                 :output :input))))))

(defun opcoes-campo-sinal (predio campo)
  (let* ((combinador (member (building-kind predio) '(:arithmetic-combinator :decider-combinator)))
         (extras (case campo
                   (:right '(nil))
                   (:left '(:each :anything :everything))
                   (:input (if combinador '(:each) '(nil)))
                   (:output (when combinador '(:each))))))
    (concatenate 'vector extras (sinais-disponiveis-circuito))))

(defun valor-campo-sinal (config campo)
  (case campo
    (:left (circuit-condition-left (circuit-device-config-condition config)))
    (:right (circuit-condition-right (circuit-device-config-condition config)))
    (:input (circuit-device-config-input-signal config))
    (:output (circuit-device-config-output-signal config))))

(defun sinais-filtrados-seletor ()
  (remove-if-not (lambda (s)
                   (or (eq *filtro-seletor-sinal* :all)
                       (eq *filtro-seletor-sinal* (if (consp s) (first s) :special))))
                 *opcoes-seletor-sinal*))

(defun abrir-seletor-sinal (predio campo)
  (when campo
    (setf *predio-seletor-sinal* predio *campo-seletor-sinal* campo
          *opcoes-seletor-sinal* (opcoes-campo-sinal predio campo)
          *filtro-seletor-sinal* :all
          *indice-seletor-sinal* (or (position (valor-campo-sinal (configuracao-circuito-padrao predio) campo)
                                             *opcoes-seletor-sinal* :test #'equal) 0)
          *pausa-antes-seletor* (paused-p) *tela-ui* :circuit-signals
          *origem-fio-circuito* nil *arrasto-construcao* nil *mensagem-menu* "")
    (garantir-pausa) t))

(defun fechar-seletor-sinal ()
  (setf *predio-seletor-sinal* nil *campo-seletor-sinal* nil *opcoes-seletor-sinal* #()
        *tela-ui* :playing)
  (unless *pausa-antes-seletor* (garantir-execucao)))

(defun aplicar-sinal-escolhido (mundo)
  (handler-case
      (let ((opcoes (sinais-filtrados-seletor)) (predio *predio-seletor-sinal*))
        (unless (and predio (eq predio (predio-por-id mundo (building-id predio))))
          (error (texto-local "CONSTRUCAO NAO ESTA MAIS DISPONIVEL" "BUILDING IS NO LONGER AVAILABLE")))
        (when (< *indice-seletor-sinal* (length opcoes))
          ;; Nunca modifica a configuração ativa antes de sua validação integral.
          (let* ((config (copy-structure (configuracao-circuito-padrao predio)))
                 (condicao (circuit-device-config-condition config))
                 (sinal (aref opcoes *indice-seletor-sinal*)))
            (when condicao (setf (circuit-device-config-condition config) (copy-structure condicao)))
            (case *campo-seletor-sinal*
              (:left (setf (circuit-condition-left (circuit-device-config-condition config)) sinal))
              (:right (setf (circuit-condition-right (circuit-device-config-condition config)) sinal))
              (:input (setf (circuit-device-config-input-signal config) sinal))
              (:output (setf (circuit-device-config-output-signal config) sinal)))
            (configure-circuit-device predio config)
            (fechar-seletor-sinal))))
    (error (e) (setf *mensagem-menu* (princ-to-string e)))))

(defun filtrar-seletor-sinal (filtro)
  (setf *filtro-seletor-sinal* filtro *indice-seletor-sinal* 0))
(defun paginar-seletor-sinal (delta)
  (let ((total (length (sinais-filtrados-seletor))))
    (when (plusp total)
      (setf *indice-seletor-sinal* (max 0 (min (1- total) (+ *indice-seletor-sinal* (* 24 delta))))))))
(defun origem-seletor-sinal ()
  (values (floor (- (screen-width) 720) 2) (floor (- (screen-height) 560) 2)))
(defun indice-clique-sinal (mx my)
  (multiple-value-bind (x y) (origem-seletor-sinal)
    (let ((dx (- mx x 24)) (dy (- my y 110)))
      (when (and (<= 0 dx) (< dx 672) (<= 0 dy) (< dy 288)
                 (< (mod dx 112) 104) (< (mod dy 72) 64))
        (let ((i (+ (* 24 (floor *indice-seletor-sinal* 24)) (* 6 (floor dy 72)) (floor dx 112))))
          (when (< i (length (sinais-filtrados-seletor))) i))))))
(defun nome-sinal-seletor (sinal)
  (cond ((null sinal) (if (eq *campo-seletor-sinal* :right)
                         (texto-local "CONSTANTE" "CONSTANT") (texto-local "SEM FILTRO" "NO FILTER")))
        ((consp sinal) (let ((d (find-item (second sinal))))
                         (if d (nome-item-inventario d) (rotulo-sinal-circuito sinal))))
        (t (string sinal))))

(defun desenhar-seletor-sinal (mundo)
  (declare (ignore mundo))
  (draw-rect 0 0 (screen-width) (screen-height) '(4 10 17 255))
  (multiple-value-bind (x y) (origem-seletor-sinal)
    (draw-rect x y 720 560 '(10 22 32 255))
    (draw-rect x y 720 560 '(65 105 121 255) :outline t)
    (draw-text (texto-local "ESCOLHER SINAL" "CHOOSE SIGNAL") (+ x 24) (+ y 20) '(112 245 220 255) :scale 2)
    (loop for filtro across *filtros-seletor-sinal* for i from 0 do
      (desenhar-botao-menu (nth i (if (eq (current-language) :pt)
                                     '("TODOS" "ITENS" "FLUIDOS" "VIRTUAIS" "ESPECIAIS")
                                     '("ALL" "ITEMS" "FLUIDS" "VIRTUAL" "SPECIAL")))
                           (+ x 24 (* i 136)) (+ y 54) 128 (eq filtro *filtro-seletor-sinal*)))
    (let* ((opcoes (sinais-filtrados-seletor)) (total (length opcoes))
           (pagina (floor *indice-seletor-sinal* 24)))
      (loop for i from (* pagina 24) below (min total (* (1+ pagina) 24))
            for s = (aref opcoes i) for cx = (+ x 24 (* (mod i 6) 112))
            for cy = (+ y 110 (* (floor (mod i 24) 6) 72)) do
        (draw-rect cx cy 104 64 (if (= i *indice-seletor-sinal*) '(23 63 72 255) '(6 14 22 255)))
        (draw-rect cx cy 104 64 (if (= i *indice-seletor-sinal*) '(112 245 220 255) '(44 75 90 255)) :outline t)
        (if (and (consp s) (find-item (second s)))
            (desenhar-icone-item (second s) (+ cx 38) (+ cy 5) 28)
            (draw-text (if (consp s) (subseq (string (second s)) 0 (min 8 (length (string (second s)))))
                           (if s (string s) "--")) (+ cx 8) (+ cy 13) '(241 193 90 255) :scale 1))
        (let ((nome (nome-sinal-seletor s)))
          (draw-text (subseq nome 0 (min 16 (length nome))) (+ cx 4) (+ cy 46) '(197 220 229 255) :scale 1)))
      (if (zerop total)
          (draw-text (texto-local "NENHUM SINAL NESTA CATEGORIA" "NO SIGNALS IN THIS CATEGORY") (+ x 24) (+ y 160) '(241 193 90 255) :scale 1)
          (let* ((s (aref opcoes *indice-seletor-sinal*))
                 (nome (nome-sinal-seletor s))
                 (identificador (rotulo-sinal-circuito s))
                 (texto (if (string-equal nome identificador) nome
                            (format nil "~A | ~A" nome identificador))))
            (draw-text (subseq texto 0 (min 108 (length texto))) (+ x 24) (+ y 410) '(112 245 220 255) :scale 1)))
      (desenhar-botao-menu "<" (+ x 24) (+ y 446) 72 nil)
      (draw-text (format nil "~D / ~D" (1+ pagina) (max 1 (ceiling total 24))) (+ x 114) (+ y 464) '(197 220 229 255) :scale 1)
      (desenhar-botao-menu ">" (+ x 208) (+ y 446) 72 nil)
      (desenhar-botao-menu (translate :back) (+ x 560) (+ y 446) 136 nil))
    (draw-text (format nil "~A/~A ~A | ~A/~A ~A | ~A/~A ~A"
                       (rotulo-tecla :scancode-return) (rotulo-botao 0) (texto-local "APLICAR" "APPLY")
                       (rotulo-tecla :scancode-tab) (rotulo-botao 2) (texto-local "CATEGORIA" "CATEGORY")
                       (rotulo-botao 9) (rotulo-botao 10) (texto-local "PAGINAS" "PAGES"))
               (+ x 24) (+ y 510) '(197 220 229 255) :scale 1)
    (draw-text (subseq *mensagem-menu* 0 (min 105 (length *mensagem-menu*))) (+ x 24) (+ y 535) '(255 137 130 255) :scale 1)))

(defun entrada-seletor-sinal (mundo tipo dados)
  (let* ((n (first dados)) (total (length (sinais-filtrados-seletor)))
         (acao (case tipo
                 (:key-down (case n (41 :back) ((40 88) :apply) (80 :left) (79 :right) (82 :up) (81 :down)
                                  (43 :filter) (75 :previous) (78 :next)))
                 (:controller-down (case n (1 :back) (0 :apply) (13 :left) (14 :right) (11 :up) (12 :down)
                                         (2 :filter) (9 :previous) (10 :next))))))
    (case acao
      (:back (fechar-seletor-sinal)) (:apply (aplicar-sinal-escolhido mundo))
      (:filter (filtrar-seletor-sinal (proximo-em-vetor *filtro-seletor-sinal* *filtros-seletor-sinal* :teste #'eq)))
      (:previous (paginar-seletor-sinal -1)) (:next (paginar-seletor-sinal 1))
      ((:left :right :up :down)
       (when (plusp total) (setf *indice-seletor-sinal*
                               (mod (+ *indice-seletor-sinal* (case acao (:left -1) (:right 1) (:up -6) (:down 6))) total)))))
    (when (eq tipo :mouse-wheel) (paginar-seletor-sinal (- (signum (second dados)))))
    (when (and (eq tipo :mouse-down) (= n 1))
      (multiple-value-bind (x y) (origem-seletor-sinal)
        (let* ((mx (second dados)) (my (third dados)) (indice (indice-clique-sinal mx my)))
          (cond (indice (setf *indice-seletor-sinal* indice) (aplicar-sinal-escolhido mundo))
                ((<= (+ y 54) my (+ y 100))
                 (let ((i (floor (- mx x 24) 136)))
                   (when (and (<= 0 i 4) (< (mod (- mx x 24) 136) 128))
                     (filtrar-seletor-sinal (aref *filtros-seletor-sinal* i)))))
                ((<= (+ y 446) my (+ y 492))
                 (cond ((<= (+ x 24) mx (+ x 96)) (paginar-seletor-sinal -1))
                       ((<= (+ x 208) mx (+ x 280)) (paginar-seletor-sinal 1))
                       ((<= (+ x 560) mx (+ x 696)) (fechar-seletor-sinal))))))))) t)

(defun ajuda-fios-remapeada ()
  (format nil "~A ~A  ~A ~A  ~A ~A"
          (if *gamepad-ativo* (rotulo-botao 3) (rotulo-tecla :scancode-c)) (texto-local "FECHA" "CLOSE")
          (if *gamepad-ativo* (rotulo-botao 2) (rotulo-tecla :scancode-x)) (texto-local "COR" "COLOR")
          (if *gamepad-ativo* (rotulo-botao 0) (format nil "M~D" (codigo-fisico :mouse 1))) (texto-local "LIGA" "LINK")))

(defun remapear-linha-guia (linha)
  (cond ((and (>= (length linha) 2) (string= linha "R " :end1 2))
         (concatenate 'string (if *gamepad-ativo* (rotulo-botao 11) (rotulo-tecla :scancode-r)) (subseq linha 1)))
        ((and (>= (length linha) 2) (string= linha "C:" :end1 2))
         (concatenate 'string (if *gamepad-ativo* (rotulo-botao 3) (rotulo-tecla :scancode-c)) (subseq linha 1)))
        (t linha)))
