;;;; Interface do jogo: controles, perfis e arquivos. Não faz parte da engine.
(in-package #:asterion-assembly)

(defun texto-local (pt en) (if (eq (current-language) :pt) pt en))
(defparameter *teclas-configuraveis*
  '(:scancode-w :scancode-a :scancode-s :scancode-d :scancode-c :scancode-x
    :scancode-q :scancode-e :scancode-r :scancode-f :scancode-b :scancode-t
    :scancode-tab :scancode-h :scancode-z :scancode-space :scancode-i
    :scancode-up :scancode-down :scancode-left :scancode-right :scancode-return
    :scancode-pageup :scancode-pagedown :scancode-f1 :scancode-f2 :scancode-f3))
(defvar *controles* nil)
(defvar *captura-controle* nil)
(defvar *retorno-painel* :settings)
(defvar *modo-arquivos* :load)
(defvar *linhas-painel* nil)
(defvar *acao-confirmada* nil)
(defvar *retorno-confirmacao* nil)
(defvar *pergunta-confirmacao* "")
(defvar *predio-inventario* nil)
(defvar *retirar-inventario* nil)
(defparameter *itens-inventario-pt*
  '((:iron-ore . "Minerio de ferro") (:copper-ore . "Minerio de cobre") (:stone . "Pedra")
    (:coal . "Carbono") (:silica . "Silica") (:oil . "Petroleo") (:water . "Agua")
    (:asterion-crystal . "Cristal Asterion") (:iron-plate . "Chapa de ferro") (:copper-plate . "Chapa de cobre")
    (:steel-plate . "Chapa de aco") (:glass . "Vidro") (:stone-brick . "Tijolo") (:copper-wire . "Fio de cobre")
    (:gear . "Engrenagem") (:pipe . "Tubo") (:circuit . "Circuito") (:advanced-circuit . "Circuito avancado")
    (:processor . "Processador") (:battery . "Bateria") (:plastic . "Bioplastico") (:sulfur . "Enxofre")
    (:lubricant . "Lubrificante") (:fuel . "Combustivel refinado") (:science-red . "Pacote de analise")
    (:science-green . "Pacote logistico") (:science-blue . "Pacote de sistemas") (:science-purple . "Pacote quantico")
    (:belt-part . "Conjunto de esteira") (:inserter-part . "Servo") (:engine . "Motor") (:electric-engine . "Motor eletrico")
    (:rail-part . "Secao de trilho") (:signal-part . "Controlador de sinal") (:drone-frame . "Chassi de drone")
    (:logistic-drone . "Drone logistico") (:repair-pack . "Kit de reparo") (:magazine . "Carregador")
    (:piercing-magazine . "Carregador perfurante") (:rocket . "Foguete") (:plasma-cell . "Celula de plasma")
    (:hive-charge . "Carga anticolmeia") (:wall-part . "Muro composto") (:solar-cell . "Celula solar")
    (:accumulator-cell . "Celula acumuladora") (:crystal-analysis . "Analise de cristal")
    (:tungsten-ore . "Minerio de tungstenio") (:cobalt-ore . "Minerio de cobalto") (:biomass . "Biomassa")
    (:tungsten-plate . "Chapa de tungstenio") (:cobalt-plate . "Chapa de cobalto") (:concrete . "Concreto")
    (:reinforced-concrete . "Concreto armado") (:motor . "Motor de precisao") (:precision-gear . "Engrenagem de precisao")
    (:pump-unit . "Unidade de bombeamento") (:sensor . "Sensor de rede") (:wire-red . "Fio vermelho")
    (:wire-green . "Fio verde") (:robot-brain . "Cerebro robotico") (:construction-drone . "Drone construtor")
    (:fluid-canister . "Recipiente de fluido") (:coolant . "Fluido refrigerante") (:explosives . "Explosivos industriais")
    (:rail-chain-controller . "Controlador de cadeia") (:pollution-filter . "Filtro de poluicao")
    (:restoration-seed . "Semente de restauracao") (:artillery-shell . "Municao de artilharia")
    (:locomotive-frame . "Chassi de locomotiva") (:wagon-frame . "Chassi de vagao")))
(defun nome-item-inventario (definicao)
  (or (when (eq (current-language) :pt) (cdr (assoc (item-definition-id definicao) *itens-inventario-pt*)))
      (item-definition-name definicao) (string (item-definition-id definicao))))
(defparameter *nomes-teclas-pt*
  '("MOVER CIMA" "MOVER ESQUERDA" "MOVER BAIXO" "MOVER DIREITA" "CIRCUITOS" "DISPARO / COR"
    "CONSTRUCAO ANTERIOR" "PROXIMA CONSTRUCAO" "GIRAR" "RECEITA" "CATALOGO" "TECNOLOGIA"
    "ESTATISTICAS / ABA" "AJUDA" "DESFAZER" "PAUSA" "INVENTARIO"
    "MENU CIMA" "MENU BAIXO" "MENU ESQUERDA" "MENU DIREITA" "CONFIRMAR"
    "PAGINA ANTERIOR" "PROXIMA PAGINA" "VELOCIDADE 1X" "VELOCIDADE 2X" "VELOCIDADE 4X"))
(defparameter *nomes-teclas-en*
  '("MOVE UP" "MOVE LEFT" "MOVE DOWN" "MOVE RIGHT" "CIRCUITS" "FIRE / WIRE COLOR"
    "PREVIOUS BUILDING" "NEXT BUILDING" "ROTATE" "RECIPE" "CATALOG" "TECHNOLOGY"
    "STATISTICS / TAB" "HELP" "UNDO" "PAUSE" "INVENTORY"
    "MENU UP" "MENU DOWN" "MENU LEFT" "MENU RIGHT" "CONFIRM"
    "PREVIOUS PAGE" "NEXT PAGE" "SPEED 1X" "SPEED 2X" "SPEED 4X"))
(defparameter *botoes-gamepad* #("A" "B" "X" "Y" "BACK" "GUIDE" "START" "L3" "R3" "LB" "RB" "UP" "DOWN" "LEFT" "RIGHT"))
(defun nome-controle (grupo codigo)
  (case grupo
    (:keyboard (nth (position codigo *teclas-configuraveis* :key #'sdl2:scancode-key-to-value)
                    (if (eq (current-language) :pt) *nomes-teclas-pt* *nomes-teclas-en*)))
    (:controller (aref (if (eq (current-language) :pt)
                          #("CONSTRUIR / CONFIRMAR" "REMOVER / CANCELAR" "DISPARO / COR" "CIRCUITOS" "ANTERIOR" "PROXIMO" "PAUSA" "VELOCIDADE" "INVENTARIO" "ANTERIOR / ABA" "PROXIMO / ABA" "GIRAR / CIMA" "RECEITA / BAIXO" "TECNOLOGIA / CAMPO" "CATALOGO / PALETA")
                          #("BUILD / CONFIRM" "REMOVE / CANCEL" "FIRE / COLOR" "CIRCUITS" "PREVIOUS" "NEXT" "PAUSE" "SPEED" "INVENTORY" "PREVIOUS / TAB" "NEXT / TAB" "ROTATE / UP" "RECIPE / DOWN" "TECHNOLOGY / FIELD" "CATALOG / PALETTE")) codigo))
    (:mouse (nth (1- codigo) (if (eq (current-language) :pt) '("CONSTRUIR / CONFIRMAR" "DISPARO" "REMOVER / CORTAR") '("BUILD / CONFIRM" "FIRE" "REMOVE / CUT"))))
    (:axes (aref (if (eq (current-language) :pt) #("MOVIMENTO X" "MOVIMENTO Y" "CURSOR X" "CURSOR Y")
                    #("MOVE X" "MOVE Y" "CURSOR X" "CURSOR Y")) codigo))))

(defun rotulo-tecla (tecla)
  (sdl2:scancode-key-name (codigo-fisico :keyboard (sdl2:scancode-key-to-value tecla))))
(defun rotulo-botao (botao)
  (aref *botoes-gamepad* (codigo-fisico :controller botao)))
(defun ajuda-controles-jogador ()
  (if *gamepad-ativo*
      (format nil "~A ~A | ~A ~A | ~A ~A | ~A ~A"
              (rotulo-botao 0) (texto-local "CONSTROI" "BUILD")
              (rotulo-botao 8) (texto-local "INVENTARIO" "INVENTORY")
              (rotulo-botao 3) (texto-local "CIRCUITOS" "CIRCUITS")
              (rotulo-botao 6) (texto-local "PAUSA" "PAUSE"))
      (format nil "~{~A~^/~} ~A | ~A ~A | ~A ~A | ~A ~A"
              (mapcar #'rotulo-tecla '(:scancode-w :scancode-a :scancode-s :scancode-d))
              (texto-local "MOVE" "MOVE")
              (rotulo-tecla :scancode-i) (texto-local "INVENTARIO" "INVENTORY")
              (rotulo-tecla :scancode-c) (texto-local "CIRCUITOS" "CIRCUITS")
              (rotulo-tecla :scancode-space) (texto-local "PAUSA" "PAUSE"))))

(defun controles-padrao ()
  (list :keyboard (mapcar (lambda (k) (let ((n (sdl2:scancode-key-to-value k))) (cons n n)))
                         *teclas-configuraveis*)
        :controller (loop for n below 15 collect (cons n n))
        :mouse '((1 . 1) (2 . 2) (3 . 3))
        :axes '((0 . 0) (1 . 1) (2 . 2) (3 . 3)) :inverted nil))
(defun dados-controles () (copy-tree (or *controles* (controles-padrao))))
(defun validar-controles (dados)
  ;; Campo ausente em perfis já existentes usa os padrões, sem quebrar formato 1.
  (when dados
    (unless (and (listp dados) (evenp (length dados))) (error "Invalid bindings / Controles invalidos"))
    (dolist (grupo '(:keyboard :controller :mouse :axes))
      (let ((pares (getf dados grupo)) (padroes (getf (controles-padrao) grupo)))
        (unless (and (listp pares) (= (length pares) (length padroes))
                     (every (lambda (p) (and (consp p) (assoc (car p) padroes)
                                            (integerp (cdr p))
                                            (case grupo
                                              (:keyboard (and (<= 4 (cdr p) 286) (not (member (cdr p) '(41 88)))))
                                              (:controller (<= 0 (cdr p) 14))
                                              (:mouse (<= 1 (cdr p) 3))
                                              (:axes (<= 0 (cdr p) 3))))) pares)
                     (= (length pares) (length (remove-duplicates pares :key #'car)))
                     (= (length pares) (length (remove-duplicates pares :key #'cdr))))
          (error "Duplicate or invalid bindings / Controles duplicados ou invalidos"))))
    (unless (and (listp (getf dados :inverted))
                 (every (lambda (v) (member v '(0 1 2 3))) (getf dados :inverted)))
      (error "Invalid axes / Eixos invalidos")))
  t)
(defun aplicar-controles (dados)
  (validar-controles dados)
  (setf *controles* (copy-tree (or dados (controles-padrao))))
  (clrhash antigonus::*entradas-ativas*) (fill *eixos-gamepad* 0.0))
(defun codigo-fisico (grupo codigo)
  (cdr (assoc codigo (getf (or *controles* (controles-padrao)) grupo))))
(defun tecla-jogo-p (tecla)
  (let ((codigo (codigo-fisico :keyboard (sdl2:scancode-key-to-value tecla))))
    (and codigo (input-down-p codigo))))
(defun trocar-controle (grupo codigo fisico)
  (unless *perfil-gravavel* (error (texto-local "SELECIONE UM PERFIL VALIDO" "SELECT A VALID PROFILE")))
  (let* ((novo (dados-controles)) (pares (getf novo grupo))
         (alvo (assoc codigo pares)) (conflito (rassoc fisico pares)))
    (unless alvo (error "Unknown binding / Controle desconhecido"))
    ;; Troca atômica: nunca deixa duas ações presas à mesma entrada.
    (when conflito (setf (cdr conflito) (cdr alvo)))
    (setf (cdr alvo) fisico)
    (persistir-controles novo)))
(defun persistir-controles (novo)
  (unless *perfil-gravavel* (error (texto-local "SELECIONE UM PERFIL VALIDO" "SELECT A VALID PROFILE")))
  (validar-controles novo)
  (let ((antes (dados-controles)))
    (aplicar-controles novo)
    (unless (salvar-configuracoes) (aplicar-controles antes) (error "Cannot save bindings / Falha ao salvar controles"))))

(defun ler-documento-ui (caminho)
  (with-open-file (s caminho :external-format :utf-8)
    (let ((*read-eval* nil)) (read s nil nil))))
(defun inicializar-perfil ()
  (setf *perfil-ativo* (or (uiop:getenv "ASTERION_PROFILE")
                          (handler-case
                              (let ((v (ler-documento-ui (merge-pathnames "profiles/active-profile.sexp" (diretorio-saves)))))
                                (and (stringp v) v))
                            (error () nil)) "default"))
  (handler-case (caminho-perfil) (error () (setf *perfil-ativo* "default"))))
(defun registrar-perfil-ativo ()
  (let* ((arquivo (merge-pathnames "profiles/active-profile.sexp" (diretorio-saves)))
         (tmp (pathname (format nil "~A.tmp" arquivo))))
    (ensure-directories-exist arquivo)
    (with-open-file (s tmp :direction :output :if-exists :supersede :external-format :utf-8)
      (write *perfil-ativo* :stream s :readably t))
    (uiop:rename-file-overwriting-target tmp arquivo)))
(defun selecionar-perfil (nome)
  (let* ((*perfil-ativo* nome)
         (caminho (caminho-perfil))
         (dados (ler-documento-ui caminho)))
    (validar-configuracoes dados)
    (let ((antes (dados-configuracoes)))
      (handler-case (progn (aplicar-configuracoes dados) (registrar-perfil-ativo))
        (error (e) (aplicar-configuracoes antes) (error e)))))
  (setf *perfil-ativo* nome *perfil-gravavel* t)
  (when *mundo-corrente-ui* (setf (dado *mundo-corrente-ui* :colorblind-circuits) *paleta-configurada*)))
(defun proximo-arquivo (prefixo tipo &optional (pasta (diretorio-saves)))
  (loop for i from 1 for p = (merge-pathnames (format nil "~A-~3,'0D.~A" prefixo i tipo) pasta)
        unless (probe-file p) return p))
(defun criar-perfil ()
  ;; Preserve o perfil padrão antes de sair dele, inclusive na primeira execução.
  (when (and *perfil-gravavel* (not (probe-file (caminho-perfil))))
    (unless (salvar-configuracoes) (error "Profile save failed / Falha ao salvar perfil")))
  (let ((arquivo (proximo-arquivo "profile" "sexp" (merge-pathnames "profiles/" (diretorio-saves)))))
    (let ((*perfil-gravavel* t))
      (unless (salvar-configuracoes arquivo) (error "Profile creation failed / Falha ao criar perfil")))
    (selecionar-perfil (pathname-name arquivo))))

(defun arquivos-save ()
  (sort (copy-list (directory (merge-pathnames "*.save" (diretorio-saves)))) #'string< :key #'namestring))
(defun descricao-save (arquivo)
  (handler-case
      (let* ((d (ler-documento-ui arquivo)) (v (getf d :antigonus-save)) (p (getf d :payload)))
        (if (eql v antigonus:+save-version+)
            (let* ((minutos (floor (getf p :tick 0) 1800))
                   (capitulo (cdr (assoc :chapter (getf p :game-data))))
                   (dificuldade (getf p :difficulty)))
              (values (format nil "~A | ~2,'0D:~2,'0D | ~A ~D | ~A"
                              (pathname-name arquivo) (floor minutos 60) (mod minutos 60)
                              (texto-local "CAP" "CH") (or capitulo 1)
                              (if (eq (current-language) :pt)
                                  (case dificuldade (:peaceful "PACIFICO") (:explorer "EXPLORADOR")
                                        (:standard "PADRAO") (:hostile "HOSTIL") (t dificuldade)) dificuldade)) t))
            (values (format nil "~A | ~A ~A" (pathname-name arquivo)
                            (texto-local "INCOMPATIVEL SCHEMA" "INCOMPATIBLE SCHEMA") v) nil)))
    (error () (values (format nil "~A | ~A" (pathname-name arquivo) (texto-local "ILEGIVEL" "UNREADABLE")) nil))))
(defun atualizar-painel ()
  (setf *linhas-painel*
        (case *tela-ui*
          (:controls
           (append
            (loop for grupo in '(:keyboard :controller :mouse :axes) append
              (loop for (codigo . fisico) in (getf (dados-controles) grupo)
                    collect (list (format nil "~A ~A > ~A" grupo
                                          (nome-controle grupo codigo)
                                          (case grupo (:keyboard (sdl2:scancode-key-name fisico))
                                                (:controller (aref *botoes-gamepad* fisico)) (otherwise fisico)))
                                  :bind grupo codigo)))
            (loop for n below 4 collect (list (format nil "~A ~D: ~A" (texto-local "INVERTER EIXO" "INVERT AXIS") n
                                                              (if (member n (getf (dados-controles) :inverted)) "ON" "OFF")) :invert n))
            (list (list (texto-local "RESTAURAR CONTROLES" "RESET CONTROLS") :reset-controls))))
          (:profiles
           (cons (list (texto-local "NOVO PERFIL (COPIAR ATUAL)" "NEW PROFILE (COPY CURRENT)") :new-profile)
                 (loop for p in (sort (directory (merge-pathnames "profiles/*.sexp" (diretorio-saves))) #'string< :key #'namestring)
                       unless (equal (pathname-name p) "active-profile")
                         collect (list (format nil "~A~A" (if (equal (pathname-name p) *perfil-ativo*) "* " "") (pathname-name p))
                                       :profile (pathname-name p)))))
          (:saves
           (append (when (eq *modo-arquivos* :save) (list (list (texto-local "NOVO SAVE MANUAL" "NEW MANUAL SAVE") :new-save)))
                   (loop for p in (arquivos-save) collect
                     (multiple-value-bind (texto valido) (descricao-save p) (list texto :save-file p valido)))))
          (:confirm (list (list (texto-local "CANCELAR" "CANCEL") :cancel)
                          (list (texto-local "CONFIRMAR" "CONFIRM") :confirm)))
          (:inventory
           (let* ((inv (if *retirar-inventario* (building-inventory *predio-inventario*)
                           (inventario-jogador *mundo-corrente-ui*))) (itens nil))
             (map-items (lambda (d) (let ((id (item-definition-id d)))
                                     (when (plusp (inventory-count inv id))
                                       (push (list (format nil "~A: ~D" (nome-item-inventario d) (inventory-count inv id)) :transfer id) itens)))))
             (cons (list (if *retirar-inventario*
                             (texto-local "RETIRAR ATE 10 DO PREDIO | TROCAR MODO" "TAKE UP TO 10 FROM BUILDING | SWITCH MODE")
                             (texto-local "INSERIR ATE 10 NO PREDIO | TROCAR MODO" "INSERT UP TO 10 INTO BUILDING | SWITCH MODE")) :transfer-mode)
                   (sort itens #'string< :key #'first))))))
  (unless (eq *tela-ui* :confirm) (setf *linhas-painel* (append *linhas-painel* (list (list (translate :back) :back)))))
  (setf *indice-menu* (min *indice-menu* (1- (length *linhas-painel*)))))
(defun abrir-seletor (tela &optional modo)
  (setf *retorno-painel* *tela-ui* *tela-ui* tela *indice-menu* 0 *mensagem-menu* "" *captura-controle* nil)
  (when modo (setf *modo-arquivos* modo))
  (setf *arrasto-construcao* nil *ultima-celula-arrasto* nil)
  (garantir-pausa) (atualizar-painel))
(defun voltar-painel ()
  (setf *captura-controle* nil *acao-confirmada* nil
        *tela-ui* (if (eq *tela-ui* :confirm) *retorno-confirmacao* *retorno-painel*) *indice-menu* 0)
  (when (eq *tela-ui* :playing) (garantir-execucao))
  (when (member *tela-ui* '(:controls :profiles :saves :inventory)) (atualizar-painel)))
(defun pedir-confirmacao (acao &optional (pergunta (texto-local "CONFIRMAR OPERACAO?" "CONFIRM OPERATION?")))
  (setf *acao-confirmada* acao *retorno-confirmacao* *tela-ui* *tela-ui* :confirm *indice-menu* 0)
  (setf *pergunta-confirmacao* pergunta *mensagem-menu* "")
  (atualizar-painel))
(defun gravar-manual (mundo caminho)
  (save-game mundo caminho)
  (setf *mensagem-menu* (texto-local "SAVE GRAVADO" "GAME SAVED"))
  (atualizar-painel))
(defun acionar-painel (mundo)
  (handler-case
    (destructuring-bind (texto acao &rest args) (nth *indice-menu* *linhas-painel*)
      (declare (ignore texto))
      (case acao
        (:back (voltar-painel)) (:cancel (voltar-painel))
        (:confirm (let ((f *acao-confirmada*)) (voltar-painel) (funcall f))))
      (case acao
        (:bind (if (eq (first args) :axes)
                   (trocar-controle :axes (second args) (mod (1+ (codigo-fisico :axes (second args))) 4))
                   (setf *captura-controle* args)))
        (:invert (let ((d (dados-controles)) (n (first args)))
                   (setf (getf d :inverted) (if (member n (getf d :inverted)) (remove n (getf d :inverted)) (cons n (getf d :inverted))))
                   (persistir-controles d)))
        (:reset-controls (pedir-confirmacao (lambda () (persistir-controles nil) (atualizar-painel))
                                           (texto-local "RESTAURAR CONTROLES PADRAO?" "RESTORE DEFAULT CONTROLS?")))
        (:new-profile (criar-perfil))
        (:profile (selecionar-perfil (first args)))
        (:new-save (gravar-manual mundo (proximo-arquivo "manual" "save")))
        (:save-file
         (destructuring-bind (f valido) args
           (unless valido (error (texto-local "SAVE INCOMPATIVEL OU ILEGIVEL; ORIGINAL PRESERVADO" "INCOMPATIBLE OR UNREADABLE SAVE; ORIGINAL PRESERVED")))
           (if (eq *modo-arquivos* :save)
               (pedir-confirmacao (lambda () (gravar-manual mundo f))
                                  (format nil "~A ~A?" (texto-local "SOBRESCREVER" "OVERWRITE") (file-namestring f)))
               (let ((novo (load-game f)))
                 (setf (dado novo :save-dir) (diretorio-saves))
                 (abrir-sessao novo)))))
        (:transfer-mode (setf *retirar-inventario* (not *retirar-inventario*)))
        (:transfer (transferir-inventario mundo (first args))))
      (when (member *tela-ui* '(:controls :profiles :saves :inventory)) (atualizar-painel)))
    (error (e) (setf *mensagem-menu* (princ-to-string e)))))

(defun desenhar-painel-jogador (mundo)
  (declare (ignore mundo))
  (draw-rect 0 0 (screen-width) (screen-height) '(5 12 22 255))
  (draw-text (format nil "~A | ~A" (case *tela-ui* (:controls (texto-local "CONTROLES" "CONTROLS"))
                       (:profiles (texto-local "PERFIS" "PROFILES")) (:saves "SAVES")
                       (:confirm (texto-local "CONFIRMACAO" "CONFIRMATION"))
                       (:inventory (texto-local "INVENTARIO" "INVENTORY"))) (or *perfil-ativo* "default"))
             60 35 '(112 245 220 255) :scale 2)
  (draw-text (format nil "~A/~A ~A | ~A/~A ~A | ESC/~A ~A"
                     (rotulo-tecla :scancode-up) (rotulo-tecla :scancode-down) (texto-local "SELECIONAR" "SELECT")
                     (rotulo-tecla :scancode-return) (rotulo-botao 0) (texto-local "APLICAR" "APPLY")
                     (rotulo-botao 1) (texto-local "VOLTAR" "BACK")) 60 72 '(190 209 220 255) :scale 1)
  (when (eq *tela-ui* :controls)
    (draw-text (texto-local "CONFLITOS TROCAM ENTRADAS. ESC SEMPRE CANCELA. MOUSE TAMBEM CONFIGURAVEL."
                            "CONFLICTS SWAP INPUTS. ESC ALWAYS CANCELS. MOUSE ALSO REMAPPABLE.") 60 94 '(242 186 76 255)))
  (when (eq *tela-ui* :inventory)
    (draw-text (format nil "~A (~D, ~D) | ~A" (building-kind *predio-inventario*)
                       (building-x *predio-inventario*) (building-y *predio-inventario*)
                       (texto-local "JOGO PAUSADO DURANTE A TRANSFERENCIA" "GAME PAUSED DURING TRANSFER"))
               60 94 '(242 186 76 255) :scale 1))
  (when (eq *tela-ui* :confirm)
    (draw-text *pergunta-confirmacao* 60 94 '(242 186 76 255) :scale 1))
  (loop for i from (* 8 (floor *indice-menu* 8)) below (min (length *linhas-painel*) (* 8 (1+ (floor *indice-menu* 8))))
        for linha = (nth i *linhas-painel*) do
          (desenhar-botao-menu (subseq (first linha) 0 (min 85 (length (first linha))))
                              60 (+ 125 (* (mod i 8) 58)) (- (screen-width) 120) (= i *indice-menu*) :escala 2))
  (draw-text (format nil "~D / ~D | ~A/~A ~A"
                     (1+ (floor *indice-menu* 8)) (ceiling (length *linhas-painel*) 8)
                     (rotulo-tecla :scancode-pageup) (rotulo-tecla :scancode-pagedown)
                     (texto-local "PAGINAS" "PAGES")) 60 605 '(242 186 76 255) :scale 1)
  (draw-text (if *captura-controle* (texto-local "PRESSIONE UMA ENTRADA DO TIPO ESCOLHIDO; ESC CANCELA"
                                               "PRESS AN INPUT OF THE CHOSEN TYPE; ESC CANCELS")
                 (subseq *mensagem-menu* 0 (min 150 (length *mensagem-menu*)))) 60 635 '(255 137 130 255) :scale 1))

(defun entrada-painel (mundo tipo dados)
  (let ((n (first dados)) (total (length *linhas-painel*)))
    (cond ((or (and (eq tipo :key-down) (= n 41)) (and (eq tipo :controller-down) (= n 1))) (voltar-painel))
          ((or (and (eq tipo :key-down) (= n 82)) (and (eq tipo :controller-down) (= n 11))) (setf *indice-menu* (mod (1- *indice-menu*) total)))
          ((or (and (eq tipo :key-down) (= n 81)) (and (eq tipo :controller-down) (= n 12))) (setf *indice-menu* (mod (1+ *indice-menu*) total)))
          ((or (and (eq tipo :key-down) (= n 75)) (and (eq tipo :controller-down) (= n 9))) (setf *indice-menu* (max 0 (- *indice-menu* 8))))
          ((or (and (eq tipo :key-down) (= n 78)) (and (eq tipo :controller-down) (= n 10))) (setf *indice-menu* (min (1- total) (+ *indice-menu* 8))))
          ((or (and (eq tipo :key-down) (member n '(40 88))) (and (eq tipo :controller-down) (= n 0))) (acionar-painel mundo))
          ((eq tipo :mouse-wheel) (setf *indice-menu* (max 0 (min (1- total) (- *indice-menu* (* 8 (signum (second dados))))))))
          ((and (eq tipo :mouse-down) (= n 1))
           (let* ((i (indice-clique-menu (second dados) (third dados) 60 125 (- (screen-width) 120) 8))
                  (indice (and i (+ i (* 8 (floor *indice-menu* 8))))))
             (when (and indice (< indice total)) (setf *indice-menu* indice) (acionar-painel mundo)))))) t)

(defun abrir-inventario (mundo)
  (multiple-value-bind (x y) (posicao-cursor-ui)
    (let ((b (predio-em-tela mundo x y)))
      (when (and b (alcance-personagem-p mundo (building-x b) (building-y b)))
        (setf *predio-inventario* b *retirar-inventario* nil *mundo-corrente-ui* mundo)
        (abrir-seletor :inventory)))))
(defun transferir-inventario (mundo item)
  (unless (and *predio-inventario* (eq *predio-inventario* (predio-por-id mundo (building-id *predio-inventario*)))
               (alcance-personagem-p mundo (building-x *predio-inventario*) (building-y *predio-inventario*)))
    (error "Building out of reach / Construcao fora de alcance"))
  (let* ((p (inventario-jogador mundo)) (b (building-inventory *predio-inventario*))
         (origem (if *retirar-inventario* b p)) (destino (if *retirar-inventario* p b))
         (q (min 10 (inventory-count origem item))))
    (when (plusp q) (inventory-remove origem item q) (inventory-add destino item q))))

(defun entrada-jogador (mundo tipo dados)
  ;; Hotplug e soltura de eixos não podem se perder durante menus ou captura.
  (when (eq tipo :controller-disconnected)
    (fill *eixos-gamepad* 0.0) (setf *gamepad-ativo* nil *captura-controle* nil)
    (return-from entrada-jogador t))
  (when (member tipo '(:controller-axis :controller-down)) (setf *gamepad-ativo* t))
  (when (member tipo '(:mouse-move :mouse-down :key-down)) (setf *gamepad-ativo* nil))
  (when *captura-controle*
    (cond ((and (eq tipo :key-down) (= (first dados) 41)) (setf *captura-controle* nil))
          ((eq tipo (case (first *captura-controle*) (:keyboard :key-down) (:controller :controller-down) (:mouse :mouse-down)))
           (handler-case
               (progn (trocar-controle (first *captura-controle*) (second *captura-controle*) (first dados))
                      (setf *captura-controle* nil) (atualizar-painel))
             (error (e) (setf *mensagem-menu* (princ-to-string e))))))
    (return-from entrada-jogador t))
  (let ((grupo (case tipo ((:key-down :key-up) :keyboard) ((:controller-down :controller-up) :controller)
                       ((:mouse-down :mouse-up) :mouse) (:controller-axis :axes))))
    (when grupo
      (let ((codigo (if (and (eq grupo :keyboard) (member (first dados) '(41 88))) (first dados)
                        (car (rassoc (first dados) (getf (dados-controles) grupo))))))
        (unless codigo (return-from entrada-jogador t))
        (setf dados (cons codigo (rest dados)))
        (when (and (eq grupo :axes) (member codigo (getf (dados-controles) :inverted)))
          (setf (second dados) (- (second dados)))))))
  (when (eq tipo :controller-axis)
    (let ((valor (max -1.0 (min 1.0 (/ (second dados) 32767.0)))))
      (setf (aref *eixos-gamepad* (first dados)) (if (< (abs valor) .18) 0.0 valor)))
    (return-from entrada-jogador t))
  (when (member *tela-ui* '(:controls :profiles :saves :confirm :inventory))
    (return-from entrada-jogador (entrada-painel mundo tipo dados)))
  (when (eq *tela-ui* :playing)
    (when (and (eq tipo :controller-down) (= (first dados) 7))
      (set-time-scale (case (time-scale) (1 2) (2 4) (t 1)))
      (return-from entrada-jogador t))
    (when (or (and (eq tipo :key-down) (= (first dados) 12)) (and (eq tipo :controller-down) (= (first dados) 8)))
      (abrir-inventario mundo) (return-from entrada-jogador t))
    (when (and (eq tipo :key-down) (member (first dados) '(58 59 60)))
      (set-time-scale (nth (- (first dados) 58) '(1 2 4))) (return-from entrada-jogador t))
    (when (and (eq tipo :controller-down) (not *modo-circuito*))
      (case (first dados)
        (9 (selecionar -1) (return-from entrada-jogador t))
        (10 (selecionar 1) (return-from entrada-jogador t))
        (11 (setf *rotacao-construcao* (mod (1+ *rotacao-construcao*) 4)) (return-from entrada-jogador t))
        (12 (setf *indice-receita* (mod (1+ *indice-receita*) (length *receitas-selecionaveis*))) (return-from entrada-jogador t))
        (13 (setf *tela-ui* :technology) (garantir-pausa) (return-from entrada-jogador t))
        (14 (setf *mostrar-catalogo* (not *mostrar-catalogo*)) (return-from entrada-jogador t)))))
  (let ((resultado (apply #'entrada-canonica mundo tipo dados)))
    ;; A engine não deve aplicar atalhos físicos antigos depois do remapeamento.
    (if (eq tipo :key-down) t resultado)))
