;;;; Regressões da ruptura 3.0 e dos grafos físicos de circuitos.
(in-package #:asterion-tests)

(defun falha-p (funcao)
  (handler-case (progn (funcall funcao) nil) (error () t)))

(defun cenario-circuito (&optional (workers 1))
  (let* ((w (make-world :seed 42 :worker-count workers))
         (sensor (place-building w :circuit-sensor 0 0))
         (combinador (place-building w :arithmetic-combinator 2 0))
         (lampada (place-building w :signal-lamp 4 0)))
    (inventory-add (building-inventory sensor) :iron-plate 9)
    (configure-circuit-device combinador
      (make-circuit-device-config :behavior :arithmetic :input-signal '(:item :iron-plate)
        :operator :/ :constant 2 :output-signal '(:virtual :signal-check)))
    (connect-circuit w sensor combinador :port-b :input)
    (connect-circuit w combinador lampada :port-a :output)
    (values w sensor combinador lampada)))

(defun teste-circuitos-3-0 ()
  (preparar)
  (let ((rede (make-circuit-network)))
    (verificar (falha-p (lambda () (circuit-write rede :untyped 1))))
    (verificar (falha-p (lambda () (circuit-write rede '(:item :iron) 1.5)))))
  (multiple-value-bind (w sensor combinador lampada) (cenario-circuito)
    (declare (ignore combinador))
    (let* ((redes (rebuild-circuit-networks w))
           (vermelha (first (circuit-network-for-port w sensor))))
      (verificar (= 2 (hash-table-count redes)) "entrada e saída não podem se curto-circuitar")
      (verificar (eq redes (rebuild-circuit-networks w)) "grafo limpo não deve reconstruir")
      (multiple-value-bind (fio criado) (connect-circuit w sensor lampada :color :green)
        (verificar criado)
        (verificar (= 3 (hash-table-count (rebuild-circuit-networks w))))
        (verificar (eq vermelha (first (circuit-network-for-port w sensor :main :red))))
        (multiple-value-bind (duplicado novo) (connect-circuit w lampada sensor :color :green)
          (verificar (eq fio duplicado)) (verificar (not novo)))
        (verificar (eq fio (disconnect-circuit w fio)))
        (verificar (not (disconnect-circuit w fio)))))
    (let ((distante (place-building w :signal-lamp 10 0)))
      (verificar (falha-p (lambda () (connect-circuit w sensor distante))))
      (verificar (falha-p (lambda () (connect-circuit w sensor lampada :port-a :missing))))
      (verificar (falha-p (lambda () (connect-circuit w sensor lampada :color :blue)))))
    (asterion-assembly::sistema-circuitos w)
    (verificar (not (getf (building-state lampada) :lamp-active)) "saída ainda não existe")
    (asterion-assembly::sistema-circuitos w)
    (verificar (getf (building-state lampada) :lamp-active))
    (let ((arquivo (merge-pathnames (format nil "antigonus-v3-~A.save" (gensym))
                                    (uiop:temporary-directory))))
      (unwind-protect
           (progn
             (save-game w arquivo)
             (let ((carregado (load-game arquivo)))
               (verificar (= (simulation-state-hash w) (simulation-state-hash carregado))
                          "fios, configurações e memória devem sobreviver ao save")
               (asterion-assembly::sistema-circuitos w)
               (asterion-assembly::sistema-circuitos carregado)
               (verificar (= (simulation-state-hash w) (simulation-state-hash carregado)))))
        (when (probe-file arquivo) (delete-file arquivo))))
    (dolist (fio (circuit-connections w lampada)) (disconnect-circuit w fio))
    (asterion-assembly::sistema-circuitos w)
    (verificar (getf (building-state lampada) :circuit-enabled)
               "desconectar deve liberar o atuador"))
  (dolist (caso '((:+ 7 3 10) (:- 7 3 4) (:* -7 3 -21) (:/ -7 3 -2)
                  (:mod 7 3 1) (:min -7 3 -7) (:max -7 3 3) (:/ 7 0 0) (:mod 7 0 0)))
    (destructuring-bind (op a b esperado) caso
      (verificar (= esperado (asterion-assembly::calcular-circuito a op b)))))
  (dolist (caso '((:< 1 2 t) (:<= 2 2 t) (:= 2 2 t) (:!= 1 2 t)
                  (:>= 2 2 t) (:> 2 1 t) (:> 1 2 nil)))
    (destructuring-bind (op a b esperado) caso
      (verificar (eql esperado (asterion-assembly::comparar-circuito a op b)))))
  (let ((sinais (make-hash-table :test #'equal)) (rede (make-circuit-network)))
    (setf (gethash '(:item :iron-plate) sinais) 3
          (gethash '(:fluid :water) sinais) 6)
    (dolist (especial '(:each :anything :everything))
      (verificar (asterion-assembly::sinais-que-passam sinais
                   (make-circuit-condition :left especial :comparator :> :constant 0))))
    (verificar (not (asterion-assembly::sinais-que-passam sinais
                     (make-circuit-condition :left :everything :comparator :> :constant 4))))
    (asterion-assembly::emitir-aritmetica (list rede)
      (make-circuit-device-config :input-signal :each :output-signal :each :operator :* :constant 2)
      sinais)
    (verificar (= 6 (gethash '(:item :iron-plate) (circuit-network-next-signals rede)))))
  ;; A mesma malha e o mesmo feedback devem ser independentes de workers.
  (let ((hashes (loop for workers in '(1 2 4) collect
                 (let ((w (cenario-circuito workers)))
                   (dotimes (i 8)
                     (let* ((x (* i 3))
                            (c (place-building w :arithmetic-combinator x 4)))
                       (configure-circuit-device c
                         (make-circuit-device-config :behavior :arithmetic
                           :input-signal '(:virtual :signal-a) :output-signal '(:virtual :signal-a)
                           :operator :+ :constant (1+ i)))
                       (connect-circuit w c c :port-a :output :port-b :input)))
                   (dotimes (i 12)
                     (incf (world-tick w)) (asterion-assembly::sistema-circuitos w))
                   (simulation-state-hash w)))))
    (verificar (apply #'= hashes)))
  ;; A ordem e a orientação de inserção dos fios não alteram IDs de componentes.
  (let (ids hashes)
    (dolist (reverso '(nil t))
      (let* ((w (make-world)) (a (place-building w :signal-lamp 0 0))
             (b (place-building w :signal-lamp 2 0)) (c (place-building w :signal-lamp 4 0)))
        (if reverso (progn (connect-circuit w c b) (connect-circuit w b a))
            (progn (connect-circuit w a b) (connect-circuit w b c)))
        (push (circuit-network-id (first (circuit-network-for-port w a))) ids)
        (push (simulation-state-hash w) hashes)))
    (verificar (= (first ids) (second ids)))
    (verificar (= (first hashes) (second hashes))))
  ;; Saves incompatíveis não são reescritos nem por SAVE-GAME.
  (let ((arquivo (merge-pathnames (format nil "antigonus-old-~A.save" (gensym))
                                  (uiop:temporary-directory))))
    (unwind-protect
         (dolist (schema '(1 2))
           (with-open-file (s arquivo :direction :output :if-exists :supersede)
             (prin1 (list :antigonus-save schema :payload nil) s))
           (let ((antes (uiop:read-file-string arquivo)))
             (verificar (falha-p (lambda () (load-game arquivo))))
             (verificar (falha-p (lambda () (save-game (make-world) arquivo))))
             (verificar (string= antes (uiop:read-file-string arquivo)))))
      (when (probe-file arquivo) (delete-file arquivo))))
  ;; O índice de autosave não depende do tick (9000 é múltiplo de três).
  (let* ((diretorio (merge-pathnames (format nil "antigonus-auto-~A/" (gensym))
                                    (uiop:temporary-directory)))
         (w (make-world)) arquivos)
    (unwind-protect
         (progn
           (dotimes (i 3)
             (setf (world-tick w) (* 9000 (1+ i)))
             (push (autosave-game w diretorio) arquivos))
           (verificar (= 3 (length (remove-duplicates arquivos :test #'equal))))
           (verificar (every #'probe-file arquivos)))
      (dolist (arquivo arquivos) (when (probe-file arquivo) (delete-file arquivo)))))
  (dolist (versao '("1.0.0" "2.0.0" "30.0.0" "3"))
    (let ((mod (antigonus::make-mod-manifest :id :legacy-test :engine-version versao
                 :content '("must-not-load.sexp") :enabled t)))
      (let ((*error-output* (make-broadcast-stream))) (load-mods (list mod)))
      (verificar (not (mod-manifest-enabled mod)))
      (verificar (null (loaded-mods)))
      (verificar (search "API" (getf (first (mod-errors)) :message)))))
  (preparar))
