;;;; Controles 3.0: aplicação real, cópia, persistência e validação atômica.
(in-package #:asterion-tests)

(defun teste-atuadores-avancados ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :difficulty :peaceful))
         (sensor (place-building w :circuit-sensor 20 -1))
         (origem (place-building w :tank 20 0))
         (bomba (place-building w :pump 21 0))
         (destino (place-building w :tank 22 0))
         (lampada (place-building w :signal-lamp 23 0))
         (alarme (place-building w :programmable-alarm 24 0)))
    (connect-circuit w sensor bomba)
    (connect-circuit w sensor lampada)
    (connect-circuit w sensor alarme)
    (configure-circuit-device bomba
      (make-circuit-device-config :behavior :actuator :pump-direction :reverse))
    (inventory-add (building-inventory destino) :water 600)
    (asterion-assembly::sistema-circuitos w)
    (asterion-assembly::sistema-fluidos w)
    (verificar (= 8 (getf (building-state origem) :fluid-volume)) "bomba inversa transfere para trás")
    (verificar (= 592 (getf (building-state destino) :fluid-volume)))
    (dolist (cor '(:amber :blue :red :green))
      (dolist (brilho '(0 25 50 75 100))
        (configure-circuit-device lampada
          (make-circuit-device-config :behavior :lamp :lamp-color cor :lamp-intensity brilho))
        (asterion-assembly::sistema-circuitos w)
        (verificar (and (eq cor (getf (building-state lampada) :lamp-color))
                        (= brilho (getf (building-state lampada) :lamp-intensity))))))
    (dolist (som '(:silent :warning :critical))
      (configure-circuit-device alarme
        (make-circuit-device-config :behavior :alarm :alarm-sound som :alarm-message :tank-full))
      (asterion-assembly::sistema-circuitos w)
      (verificar (getf (building-state alarme) :alarm-active)))
    (let ((dados (antigonus::valor-para-dados
                   (asterion-assembly::configuracao-circuito-padrao alarme))))
      (verificar (equal dados (antigonus::valor-para-dados (antigonus::dados-para-valor dados)))))
    (let* ((config (make-circuit-device-config :lamp-intensity 40 :pump-direction :reverse))
           (invalida (make-circuit-device-config :lamp-intensity 101)))
      (configure-circuit-device lampada config)
      (setf (circuit-device-config-lamp-intensity config) 0)
      (verificar (= 40 (circuit-device-config-lamp-intensity
                        (asterion-assembly::configuracao-circuito-padrao lampada))))
      (verificar (falha-p (lambda () (configure-circuit-device lampada invalida))))
      (verificar (= 40 (circuit-device-config-lamp-intensity
                        (asterion-assembly::configuracao-circuito-padrao lampada)))))
    (let ((arquivo (merge-pathnames (format nil "actuators-~A.save" (gensym)) (uiop:temporary-directory))))
      (unwind-protect
           (progn (save-game w arquivo)
                  (verificar (= (simulation-state-hash w) (simulation-state-hash (load-game arquivo)))))
        (when (probe-file arquivo) (delete-file arquivo))))
    (disconnect-circuit w (first (circuit-connections w bomba)))
    (asterion-assembly::sistema-circuitos w)
    (verificar (not (getf (building-state bomba) :circuit-reverse))))
  ;; Saída preferencial e desvio quando a primeira não existe, sem perder pilhas.
  (let* ((w (make-world))
         (divisor (place-building w :splitter 0 0))
         (primeira (place-building w :belt 1 0))
         (segunda (place-building w :belt 0 1))
         (pista (aref (asterion-assembly::pistas-predio divisor) 0)))
    (setf (getf (building-state divisor) :circuit-priority) :second)
    (belt-lane-insert pista :iron-ore :position 65535 :stack 4)
    (verificar (eq segunda (asterion-assembly::destino-transportador w divisor 0)))
    (asterion-assembly::transferir-frente-pista w divisor 0)
    (verificar (= 4 (contar-item-transportador segunda :iron-ore)))
    (setf (getf (building-state divisor) :circuit-priority) :first)
    (remove-building w (building-id primeira))
    (belt-lane-insert pista :copper-ore :position 65535 :stack 3)
    ;; Libera a entrada da mesma pista na saída secundária.
    (advance-belt-lane (aref (asterion-assembly::pistas-predio segunda) 0) 8000)
    (asterion-assembly::transferir-frente-pista w divisor 0)
    (verificar (= 3 (contar-item-transportador segunda :copper-ore)) "overflow usa a outra saída")
    (verificar (zerop (contar-item-transportador divisor :copper-ore)))
    (setf (getf (building-state divisor) :circuit-filter) '(:item :iron-ore))
    (belt-lane-insert pista :iron-ore :position 65535 :stack 2)
    (verificar (null (asterion-assembly::destino-transportador w divisor 0)))
    (asterion-assembly::transferir-frente-pista w divisor 0)
    (verificar (= 2 (contar-item-transportador divisor :iron-ore)) "filtro não vaza para saída errada")
    (setf (getf (building-state divisor) :circuit-priority) :second)
    (verificar (eq segunda (asterion-assembly::destino-transportador w divisor 0))))
  ;; Os mesmos cartões usados pelo mouse são acessíveis por gamepad.
  (let* ((w (make-world)) (b (place-building w :pump 0 0))
         (asterion-assembly::*modo-circuito* t)
         (asterion-assembly::*tela-ui* :playing)
         (asterion-assembly::*pagina-dispositivo-circuito* 0)
         (asterion-assembly::*predio-circuito-selecionado* b)
         (asterion-assembly::*cursor-gamepad-x* (- (screen-width) 50)))
    (asterion-assembly::entrada w :controller-down 10)
    (verificar (= 1 asterion-assembly::*pagina-dispositivo-circuito*))
    (asterion-assembly::entrada w :controller-down 0)
    (verificar (eq :reverse (circuit-device-config-pump-direction
                              (asterion-assembly::configuracao-circuito-padrao b)))))
  (verificar (> (length (asterion-assembly::sinais-disponiveis-circuito)) 70)))

(defun teste-configuracoes-persistentes ()
  (let* ((w (asterion-assembly:new-game)) (antes (simulation-state-hash w)))
    (setf (gethash :save-dir (world-game-data w)) #P"another-location/saves/")
    (verificar (= antes (simulation-state-hash w)) "hash industrial independe da pasta do jogador"))
  (let* ((antes (asterion-assembly::dados-configuracoes))
         (novo (copy-list antes))
         (arquivo (merge-pathnames (format nil "profile-~A.sexp" (gensym)) (uiop:temporary-directory)))
         (asterion-assembly::*perfil-gravavel* t))
    (unwind-protect
         (progn
           (setf (getf novo :language) :pt (getf novo :master-volume) 64
                 (getf novo :effects-volume) 32 (getf novo :alerts-volume) 96
                 (getf novo :resolution) '(1600 900) (getf novo :ui-scale) 3/4
                 (getf novo :colorblind) t)
           (asterion-assembly::aplicar-configuracoes novo)
           (verificar (= 1707 (screen-width)))
           (verificar (= 960 (screen-height)))
           (verificar (= 16 (antigonus::volume-efetivo-canal :effects)))
           (verificar (= 48 (antigonus::volume-efetivo-canal :alerts)))
           (verificar (asterion-assembly::salvar-configuracoes arquivo))
           (asterion-assembly::aplicar-configuracoes antes)
           (asterion-assembly::carregar-configuracoes arquivo)
           (verificar (equal novo (asterion-assembly::dados-configuracoes)))
           (let ((invalido (copy-list novo)))
             (setf (getf invalido :master-volume) 900)
             (verificar (falha-p (lambda () (asterion-assembly::aplicar-configuracoes invalido))))
             (verificar (equal novo (asterion-assembly::dados-configuracoes))))
           (with-open-file (s arquivo :direction :output :if-exists :supersede)
             (write-string "#.(error \"reader eval forbidden\")" s))
           (asterion-assembly::carregar-configuracoes arquivo)
           (verificar (not asterion-assembly::*perfil-gravavel*))
           (verificar (not (asterion-assembly::salvar-configuracoes arquivo)))
           (verificar (search "#.(error" (uiop:read-file-string arquivo))))
      (asterion-assembly::aplicar-configuracoes antes)
      (when (probe-file arquivo) (delete-file arquivo)))))
