;;;; Jornada pela fila SDL. Somente leitura do mundo; construção, itens, fios e
;;;; configurações entram pelos mesmos controles do jogador, nunca por fixtures.
(load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
(pushnew (uiop:getcwd) asdf:*central-registry* :test #'equal)
(ql:quickload :asterion-assembly :silent t)
(in-package #:asterion-assembly)
(defvar *teste-gamepad* (equal (uiop:getenv "ASTERION_TEST_INPUT") "gamepad"))
(defvar *teste-joystick* nil)
(defvar *teste-soltar* nil)
(defvar *teste-espera* 0)
(defvar *teste-frame* 0)
(defvar *teste-passo* 0)
(defvar *teste-passo-frame* 0)
(defvar *teste-movimento* nil)
(defvar *teste-inventario-capturado* nil)
(defvar *teste-pasta* (or (uiop:getenv "ASTERION_TEST_OUTPUT")
                         (format nil "build/first-hour-~A/" (if *teste-gamepad* "gamepad" "mouse"))))
(defun evento-tecla-teste (codigo pressionada)
  (sdl2::c-let ((ev sdl2-ffi:sdl-event :free t))
    (setf (ev :type) (sdl2::get-event-code (if pressionada :keydown :keyup))
          (ev :key :state) (if pressionada 1 0)
          (ev :key :keysym :scancode) codigo)
    (sdl2:push-event ev)))
(defun evento-mouse-teste (tipo x y &optional (botao 1))
  (sdl2::c-let ((ev sdl2-ffi:sdl-event :free t))
    (setf (ev :type) (sdl2::get-event-code tipo))
    (if (eq tipo :mousemotion)
        (setf (ev :motion :x) (round x) (ev :motion :y) (round y))
        (setf (ev :button :button) botao (ev :button :x) (round x) (ev :button :y) (round y)))
    (sdl2:push-event ev)))
(defun botao-teste (n valor)
  (assert (zerop (cffi:foreign-funcall "SDL_JoystickSetVirtualButton" :pointer *teste-joystick* :int n :uint8 valor :int))))
(defun eixo-teste (n valor)
  (assert (zerop (cffi:foreign-funcall "SDL_JoystickSetVirtualAxis" :pointer *teste-joystick* :int n :int16 valor :int))))
(defun pulso-teste (tecla botao)
  (if *teste-gamepad*
      (progn (botao-teste botao 1) (setf *teste-soltar* (lambda () (botao-teste botao 0))))
      (let ((n (sdl2:scancode-key-to-value tecla)))
        (evento-tecla-teste n t) (setf *teste-soltar* (lambda () (evento-tecla-teste n nil)))))
  (setf *teste-espera* 2) nil)
(defun apontar-teste (x y)
  (if *teste-gamepad*
      (let ((dx (- x *cursor-gamepad-x*)) (dy (- y *cursor-gamepad-y*)))
        (eixo-teste 2 (if (< (abs dx) 4) 0 (round (* (signum dx) (min 26000 (max 7000 (* 700 (abs dx))))))))
        (eixo-teste 3 (if (< (abs dy) 4) 0 (round (* (signum dy) (min 26000 (max 7000 (* 700 (abs dy))))))))
        (and (< (abs dx) 4) (< (abs dy) 4)))
      (progn (evento-mouse-teste :mousemotion x y) t)))
(defun clicar-teste (x y)
  (when (apontar-teste x y)
    (if *teste-gamepad* (pulso-teste nil 0)
        (progn (evento-mouse-teste :mousebuttondown x y)
               (setf *teste-soltar* (lambda () (evento-mouse-teste :mousebuttonup x y)) *teste-espera* 2))) t))
(defun apontar-predio-teste (x y &optional porta)
  (world-to-screen (* 32 (+ x (case porta (:input .18) (:output .82) (t .5)))) (* 32 (+ y .5))))
(defun modo-teste (ativo)
  (if (eq (not (null *modo-circuito*)) ativo) t (progn (pulso-teste :scancode-c 3) nil)))
(defun selecionar-dispositivo-teste (w x y)
  (and (modo-teste t)
       (or (eq (building-at w x y) *predio-circuito-selecionado*)
           (progn
             (if *origem-fio-circuito* (pulso-teste :scancode-escape 1)
                 (multiple-value-bind (sx sy) (apontar-predio-teste x y (if (member (building-kind (building-at w x y)) '(:arithmetic-combinator :decider-combinator)) :input :main))
                   (clicar-teste sx sy))) nil))))
(defun ler-campo-teste (b n)
  (let* ((c (configuracao-circuito-padrao b)) (condicao (circuit-device-config-condition c)))
    (case n (0 (getf (building-state b) :sensor-mode :inventory))
          (1 (cond ((eq (building-kind b) :circuit-sensor) (circuit-device-config-output-signal c))
                   (condicao (circuit-condition-left condicao)) (t (circuit-device-config-input-signal c))))
          (2 (if condicao (circuit-condition-comparator condicao) (circuit-device-config-operator c)))
          (3 (if condicao (circuit-condition-constant condicao) (circuit-device-config-constant c)))
          (4 (if (member (building-kind b) '(:arithmetic-combinator :decider-combinator)) (circuit-device-config-output-signal c) (circuit-device-config-input-signal c))))))
(defun executar-passo-teste (w cmd)
  (case (first cmd)
    (:start (if (eq *tela-ui* :playing) t (progn (pulso-teste :scancode-return 0) nil)))
    (:speed (if (= (time-scale) 4) t (progn (pulso-teste :scancode-f3 7) nil)))
    (:move
     (let* ((p (personagem w)) (direcao (second cmd))
            (tecla (if (plusp direcao) 7 4)))
       (unless *teste-movimento*
         (setf *teste-movimento* (entity-x p))
         (if *teste-gamepad* (eixo-teste 0 (* direcao 24000)) (evento-tecla-teste tecla t)))
       (when (>= (* direcao (- (entity-x p) *teste-movimento*)) 1)
         (if *teste-gamepad* (eixo-teste 0 0) (evento-tecla-teste tecla nil))
         (capture-renderer (format nil "~Amove-~D.ppm" *teste-pasta* direcao))
         (setf *teste-movimento* nil *teste-espera* 5) t)))
    (:build
     (destructuring-bind (op tipo x y &optional (rot 0)) cmd
       (declare (ignore op))
       (or (let ((b (building-at w x y))) (and b (eq (building-kind b) tipo)))
           (when (modo-teste nil)
             (cond ((not (eq (aref *selecionados* *indice-selecao*) tipo)) (pulso-teste :scancode-e 10))
                   ((/= *rotacao-construcao* rot) (pulso-teste :scancode-r 11))
                   (t (multiple-value-bind (sx sy) (apontar-predio-teste x y) (clicar-teste sx sy)))) nil))))
    (:chapter
     (when (>= (dado w :chapter) (second cmd))
       (capture-renderer (format nil "~Achapter-~D.ppm" *teste-pasta* (second cmd)))
       (format t "~&JOURNEY CHAPTER ~D at tick ~D~%" (second cmd) (world-tick w)) t))
    (:field
     (destructuring-bind (op x y linha valor) cmd
       (declare (ignore op))
       (when (selecionar-dispositivo-teste w x y)
         (cond ((plusp *pagina-dispositivo-circuito*) (pulso-teste :scancode-tab 9) nil)
               ((equal (ler-campo-teste (building-at w x y) linha) valor) t)
               (*teste-gamepad*
                (when (apontar-teste (- (screen-width) 100) (+ 240 (* linha 42)))
                  (if (/= *campo-circuito-gamepad* linha) (pulso-teste nil 13) (pulso-teste nil 0))) nil)
               (t (clicar-teste (- (screen-width) 50) (+ 240 (* linha 42))) nil)))))
    (:wire
     (destructuring-bind (op ax ay pa bx by pb) cmd
       (declare (ignore op))
       (let ((a (building-at w ax ay)) (b (building-at w bx by)))
         (or (find-if (lambda (f) (and (= (circuit-wire-a-building f) (building-id a))
                                       (= (circuit-wire-b-building f) (building-id b))
                                       (eq (circuit-wire-a-port f) pa) (eq (circuit-wire-b-port f) pb))) (circuit-connections w))
             (when (modo-teste t)
               (cond ((and *origem-fio-circuito* (or (not (eq a *origem-fio-circuito*)) (not (eq pa *porta-origem-circuito*))))
                      (pulso-teste :scancode-escape 1))
                     (t (multiple-value-bind (x y) (if *origem-fio-circuito* (apontar-predio-teste bx by pb) (apontar-predio-teste ax ay pa))
                          (clicar-teste x y)))) nil)))))
    (:stock
     (destructuring-bind (op x y item q) cmd
       (declare (ignore op)) (>= (inventory-count (building-inventory (building-at w x y)) item) q)))
    (:inventory
     (destructuring-bind (op x y item retirar &optional (quantidade 10)) cmd
       (declare (ignore op))
       (cond ((eq *tela-ui* :playing)
              (when (modo-teste nil)
                (multiple-value-bind (sx sy) (apontar-predio-teste x y)
                  (when (apontar-teste sx sy) (pulso-teste :scancode-i 8)))) nil)
             ((eq *tela-ui* :inventory)
              (unless *teste-inventario-capturado*
                (capture-renderer (format nil "~Ainventory.ppm" *teste-pasta*))
                (setf *teste-inventario-capturado* t))
              (let* ((b (building-at w x y))
                     (q (inventory-count (building-inventory b) item))
                     (feito (if retirar (zerop q) (>= q quantidade)))
                     (indice (if (not (eq *retirar-inventario* retirar)) 0
                                 (position item *linhas-painel* :key #'third))))
                (cond (feito (pulso-teste :scancode-escape 1) t)
                      ((null indice) (error "Item unavailable through inventory UI: ~S" cmd))
                      ((/= indice *indice-menu*) (pulso-teste :scancode-down 12) nil)
                      (t (pulso-teste :scancode-return 0) nil)))))))
    (:close-circuits (modo-teste nil))
    (:hour (>= (world-tick w) (if (uiop:getenv "ASTERION_SHORT_JOURNEY") 3600 108000)))
    (:pause (if (eq *tela-ui* :pause) t (progn (pulso-teste :scancode-space 6) nil)))
    (:back (pulso-teste :scancode-escape 1) t)
    (:manual
     (if (find "manual-001" (arquivos-save) :key #'pathname-name :test #'equal) t
         (progn (pulso-teste :scancode-return 0) nil)))
    (:menu
     (destructuring-bind (op tela indice) cmd (declare (ignore op))
       (if (not (eq *tela-ui* tela)) t
           (progn (if (/= *indice-menu* indice) (pulso-teste :scancode-down 12) (pulso-teste :scancode-return 0)) nil))))
    (:saved
     (let ((arquivos (arquivos-save)))
       (assert (find "manual-001" arquivos :key #'pathname-name :test #'equal))
       (unless (uiop:getenv "ASTERION_SHORT_JOURNEY")
         (assert (= 3 (count-if (lambda (p) (search "autosave-" (pathname-name p))) arquivos))))
       (dolist (f arquivos)
         (let ((carregado (load-game f)))
           (when (or (not (uiop:getenv "ASTERION_SHORT_JOURNEY")) (equal (pathname-name f) "manual-001"))
             (assert (>= (dado carregado :chapter) 7))
             (assert (= (length (circuit-connections carregado)) (length (circuit-connections w))))))) t))
    (:load-manual
     (if (eq *tela-ui* :playing) t
         (let ((indice (position-if (lambda (l) (and (eq (second l) :save-file)
                                                    (equal (pathname-name (third l)) "manual-001"))) *linhas-painel*)))
           (assert indice)
           (if (/= *indice-menu* indice) (pulso-teste :scancode-down 12) (pulso-teste :scancode-return 0)) nil)))
    (:load-latest
     (if (eq *tela-ui* :playing)
         (progn (assert (>= (dado w :chapter) 7))
                (format t "~&RESUMED THROUGH SAVE UI: tick ~D~%" (world-tick w)) t)
         (let* ((arquivo (first (sort (arquivos-save) #'>
                                     :key (lambda (p) (getf (getf (ler-documento-ui p) :payload) :tick)))))
                (indice (position arquivo *linhas-painel* :key #'third :test #'equal)))
           (assert indice)
           (if (/= *indice-menu* indice) (pulso-teste :scancode-down 12) (pulso-teste :scancode-return 0)) nil)))
    (:finish
     (assert (eq *tela-ui* :playing))
     (assert (>= (dado w :chapter) 7))
     (capture-renderer (format nil "~Afinal.ppm" *teste-pasta*))
     (format t "~&FIRST HOUR INPUT JOURNEY OK: ~A; ticks ~D; chapter ~D; wires ~D~%"
             (if *teste-gamepad* "GAMEPAD" "KEYBOARD/MOUSE") (world-tick w) (dado w :chapter) (length (circuit-connections w)))
     (stop-game) t)))

(defparameter *roteiro-teste*
  '((:start) (:move 1) (:move -1) (:speed)
    (:build :miner -4 -4) (:build :belt -3 -4) (:build :stone-furnace -2 -4) (:chapter 2)
    (:build :solar-panel 2 2) (:chapter 3)
    (:build :logistic-chest -4 -1) (:build :inserter -3 -1) (:build :logistic-chest -2 -1)
    (:build :circuit-sensor -5 -1) (:wire -5 -1 :main -3 -1 :main)
    (:field -3 -1 1 (:item :iron-plate)) (:inventory -4 -1 :iron-plate nil) (:chapter 4)
    (:build :miner -5 -3) (:build :miner 4 -4)
    (:build :splitter 3 0) (:build :belt 4 0) (:build :belt 3 1 1)
    (:wire -5 -1 :main 3 0 :main) (:field 3 0 2 :>=) (:field 3 0 4 (:item :iron-ore))
    (:stock -5 -3 :iron-ore 4) (:stock 4 -4 :copper-ore 4)
    (:inventory -5 -3 :iron-ore t) (:inventory 4 -4 :copper-ore t)
    (:inventory 3 0 :iron-ore nil 1) (:inventory 3 0 :copper-ore nil 1) (:chapter 5)
    (:build :pump 0 7) (:build :circuit-sensor 1 6 1) (:wire 1 6 :main 0 7 :main)
    (:field 1 6 0 :fluid) (:field 1 6 1 (:fluid :water))
    (:field 0 7 1 (:fluid :water)) (:field 0 7 2 :<) (:field 0 7 3 100)
    (:build :tank 1 7) (:chapter 6)
    (:build :arithmetic-combinator -3 3) (:build :signal-lamp -1 3) (:build :programmable-alarm 1 3)
    (:field -3 3 1 (:virtual :signal-a)) (:field -3 3 2 :+)
    (:field -1 3 1 (:virtual :signal-a)) (:field 1 3 1 (:virtual :signal-a))
    (:wire -3 3 :output -3 3 :input) (:wire -3 3 :output -1 3 :main) (:wire -3 3 :output 1 3 :main)
    (:chapter 7) (:close-circuits) (:hour) (:pause) (:menu :pause 1) (:manual) (:saved)
    (:back) (:menu :pause 3) (:menu :main-menu 1) (:load-manual) (:finish)))

(unless (uiop:getenv "ASTERION_JOURNEY_LIBRARY")
(when (uiop:getenv "ASTERION_RESUME_JOURNEY")
  ;; Recuperação explícita de uma execução longa interrompida. Não monta fixtures.
  (setf *roteiro-teste* '((:menu :main-menu 1) (:load-latest) (:speed) (:hour)
                         (:pause) (:menu :pause 1) (:manual) (:saved) (:back)
                         (:menu :pause 3) (:menu :main-menu 1) (:load-manual) (:finish))))
(preparar :safe-mode t) (aplicar-controles nil)
(setf *pular-menu-principal* nil *dificuldade-atual* :peaceful)
(ensure-directories-exist (format nil "~Afinal.ppm" *teste-pasta*))
(run-game
 (define-game :title "Asterion first-hour input journey" :start #'iniciar-mundo
   :update #'atualizar :input #'entrada
   :render (lambda (w alpha)
     (incf *teste-frame*) (renderizar w alpha)
     (when (and *teste-gamepad* (= *teste-frame* 1))
       (let ((id (cffi:foreign-funcall "SDL_JoystickAttachVirtual" :int 1 :int 4 :int 15 :int 0 :int)))
         (assert (>= id 0))
         (setf *teste-joystick* (cffi:foreign-funcall "SDL_JoystickOpen" :int id :pointer))))
     (when (> *teste-frame* 10)
       (cond (*teste-soltar* (funcall *teste-soltar*) (setf *teste-soltar* nil))
             ((plusp *teste-espera*) (decf *teste-espera*))
             (t
              (let ((cmd (nth *teste-passo* *roteiro-teste*)))
                (when (and (not (eq (first cmd) :hour)) (> (- *teste-frame* *teste-passo-frame*) 12000))
                  (error "Journey stalled: ~S; message ~S; inventory ~S" cmd *mensagem-menu* (inventario-jogador w)))
                (when (executar-passo-teste w cmd)
                  (incf *teste-passo*) (setf *teste-passo-frame* *teste-frame*)
                  (format t "~&INPUT STEP ~D: ~S~%" *teste-passo* cmd))))))))
 :world (new-game :difficulty :peaceful)))
