;;;; Testes isolados de remapeamento e seletores. Não são o playtest de campanha.
(in-package #:asterion-assembly)
(defun verificar-paineis ()
  (let* ((*raiz* (merge-pathnames (format nil "asterion-ui-~D-~D/" (get-universal-time) (get-internal-real-time)) (uiop:temporary-directory)))
         (*perfil-ativo* "default") (*perfil-gravavel* t) (*controles* nil)
         (*tela-ui* :pause) (*indice-menu* 0) (*captura-controle* nil)
         (*linhas-painel* nil) (*mensagem-menu* "") (*acao-confirmada* nil)
         (*mundo-corrente-ui* (new-game :difficulty :peaceful))
         (mundo *mundo-corrente-ui*) (antes (dados-configuracoes)))
    (unwind-protect
      (progn
        (asterion-tests::verificar (salvar-configuracoes))
        (trocar-controle :keyboard 4 7)
        (asterion-tests::verificar (= 7 (codigo-fisico :keyboard 4)))
        (asterion-tests::verificar (= 4 (codigo-fisico :keyboard 7)))
        (setf (gethash 7 antigonus::*entradas-ativas*) t)
        (asterion-tests::verificar (tecla-jogo-p :scancode-a))
        (asterion-tests::verificar (not (tecla-jogo-p :scancode-d)))
        (let ((d (dados-controles)))
          (setf (cdr (first (getf d :keyboard))) 41)
          (asterion-tests::verificar (asterion-tests::falha-p (lambda () (validar-controles d)))))
        (trocar-controle :controller 3 2)
        (setf *tela-ui* :playing *modo-circuito* nil)
        (entrada mundo :controller-down 2)
        (asterion-tests::verificar *modo-circuito*)
        (setf *modo-circuito* nil)
        (trocar-controle :axes 0 2)
        (entrada mundo :controller-axis 2 20000)
        (asterion-tests::verificar (> (aref *eixos-gamepad* 0) .5))
        (setf *tela-ui* :pause)
        (entrada mundo :controller-axis 2 0)
        (asterion-tests::verificar (zerop (aref *eixos-gamepad* 0)))
        (setf *tela-ui* :controls *captura-controle* '(:controller 0))
        (entrada mundo :controller-disconnected)
        (asterion-tests::verificar (every #'zerop *eixos-gamepad*))
        (asterion-tests::verificar (null *captura-controle*))
        (let ((d (dados-controles)))
          (setf (getf d :inverted) '(0)) (aplicar-controles d)
          (entrada mundo :controller-axis 2 20000)
          (asterion-tests::verificar (< (aref *eixos-gamepad* 0) -.5)))
        (aplicar-controles nil) (carregar-configuracoes)
        (asterion-tests::verificar (= 2 (codigo-fisico :controller 3)))
        (criar-perfil)
        (asterion-tests::verificar (equal *perfil-ativo* "profile-001"))
        (trocar-controle :keyboard 4 5)
        (selecionar-perfil "default")
        (asterion-tests::verificar (= 7 (codigo-fisico :keyboard 4)))
        (selecionar-perfil "profile-001")
        (asterion-tests::verificar (= 5 (codigo-fisico :keyboard 4)))
        (inicializar-perfil)
        (asterion-tests::verificar (equal *perfil-ativo* "profile-001"))
        (let ((p (merge-pathnames "profiles/broken.sexp" (diretorio-saves))))
          (with-open-file (s p :direction :output :if-exists :supersede) (write-string "#.(error \"NO\")" s))
          (asterion-tests::verificar (asterion-tests::falha-p (lambda () (selecionar-perfil "broken"))))
          (asterion-tests::verificar (equal *perfil-ativo* "profile-001"))
          (asterion-tests::verificar (equal "#.(error \"NO\")" (uiop:read-file-string p))))
        (aplicar-controles nil)
        (setf *tela-ui* :pause)
        (abrir-seletor :saves :save)
        (acionar-painel mundo)
        (asterion-tests::verificar (= 1 (length (arquivos-save))))
        (let* ((f (first (arquivos-save))) (bytes (uiop:read-file-string f)))
          (setf *indice-menu* 1) (incf (world-tick mundo))
          (acionar-painel mundo)
          (asterion-tests::verificar (eq *tela-ui* :confirm))
          (acionar-painel mundo)
          (asterion-tests::verificar (equal bytes (uiop:read-file-string f)))
          (setf *indice-menu* 1) (acionar-painel mundo)
          (setf *indice-menu* 1) (acionar-painel mundo)
          (asterion-tests::verificar (not (equal bytes (uiop:read-file-string f))))
          (asterion-tests::verificar (= (simulation-state-hash mundo) (simulation-state-hash (load-game f))))
          (setf *modo-arquivos* :load *indice-menu* 0) (atualizar-painel) (acionar-painel mundo)
          (asterion-tests::verificar (eq *tela-ui* :playing)))
        (let ((f (merge-pathnames "old.save" (diretorio-saves))))
          (with-open-file (s f :direction :output :if-exists :supersede) (write '(:antigonus-save 2 :payload nil) :stream s))
          (multiple-value-bind (texto valido) (descricao-save f)
            (declare (ignore texto)) (asterion-tests::verificar (not valido)))
          (let ((bytes (uiop:read-file-string f)))
            (setf *tela-ui* :pause) (abrir-seletor :saves :save)
            (setf *indice-menu* (position f *linhas-painel* :key #'third :test #'equal))
            (acionar-painel mundo)
            (asterion-tests::verificar (eq *tela-ui* :saves))
            (asterion-tests::verificar (equal bytes (uiop:read-file-string f)))))
        (let* ((b (place-building mundo :logistic-chest 1 2)) (*predio-inventario* b)
               (*retirar-inventario* nil) (q (inventory-count (inventario-jogador mundo) :iron-plate)))
          (transferir-inventario mundo :iron-plate)
          (asterion-tests::verificar (= 10 (inventory-count (building-inventory b) :iron-plate)))
          (setf *retirar-inventario* t) (transferir-inventario mundo :iron-plate)
          (asterion-tests::verificar (= q (inventory-count (inventario-jogador mundo) :iron-plate)))))
      (aplicar-configuracoes antes) (fill *eixos-gamepad* 0.0) (setf *modo-circuito* nil)
      (garantir-execucao))))
(in-package #:asterion-tests)
(defun teste-paineis-jogador () (preparar) (asterion-assembly::verificar-paineis))
