;;;; Navegação e captura reais na fila SDL, em diretório de saves descartável.
;;;; Execute com ASTERION_JOURNEY_LIBRARY=1 para importar somente os auxiliares.
(load "tests/first-hour-playtest.lisp")
(in-package #:asterion-assembly)
(assert (uiop:getenv "ASTERION_JOURNEY_LIBRARY"))
(defvar *etapa-ui* 0)
(defvar *fase-ui* nil)
(defvar *bytes-ui* nil)
(defvar *y-ui* nil)
(defvar *ui-gamepad* nil)
(defun pulso-ui (tecla botao)
  (let ((*teste-gamepad* *ui-gamepad*))
    (if *ui-gamepad* (pulso-teste nil (codigo-fisico :controller botao))
        (let ((fisico (if (= tecla 41) 41 (codigo-fisico :keyboard tecla))))
               (evento-tecla-teste fisico t)
               (setf *teste-soltar* (lambda () (evento-tecla-teste fisico nil))
                     *teste-espera* 2)))) nil)
(defun escolher-ui (indice)
  (if (/= *indice-menu* indice) (pulso-ui 81 12) (pulso-ui 40 0)))
(defun achar-linha-ui (acao &optional argumento)
  (or (position-if (lambda (linha) (and (eq (second linha) acao)
                                      (or (null argumento) (equal (third linha) argumento)))) *linhas-painel*)
      (error "Linha ausente: ~S ~S" acao argumento)))
(defun executar-ui (w cmd)
  (case (first cmd)
    (:setting
     (let ((atual (case (second cmd) (0 (current-language)) (3 *resolucao-configurada*) (5 *escala-ui-configurada*))))
       (if (equal atual (third cmd)) t (escolher-ui (second cmd)))))
    (:menu (if (not (eq *tela-ui* (second cmd))) t (escolher-ui (third cmd))))
    (:back (pulso-ui 41 1) t)
    (:input-mode (setf *ui-gamepad* (second cmd)) t)
    (:bind
     (destructuring-bind (op grupo codigo fisico) cmd
       (declare (ignore op))
       (cond ((= (codigo-fisico grupo codigo) fisico)
              (assert (null *captura-controle*)) t)
             (*captura-controle*
              (case grupo
                (:keyboard (evento-tecla-teste fisico t)
                           (setf *teste-soltar* (lambda () (evento-tecla-teste fisico nil))))
                (:controller (botao-teste fisico 1) (setf *teste-soltar* (lambda () (botao-teste fisico 0))))
                (:mouse (evento-mouse-teste :mousebuttondown 500 150 fisico)
                        (setf *teste-soltar* (lambda () (evento-mouse-teste :mousebuttonup 500 150 fisico)))))
              (setf *teste-espera* 2) nil)
             (t (escolher-ui (position-if (lambda (l) (and (eq (second l) :bind) (eq (third l) grupo) (= (fourth l) codigo))) *linhas-painel*))))))
    (:shot (capture-renderer (format nil "build/player-ui-playtest/~A.ppm" (second cmd))) t)
    (:profile-new
     (if (equal *perfil-ativo* "profile-001") t (escolher-ui (achar-linha-ui :new-profile))))
    (:profile
     (if (equal *perfil-ativo* (second cmd)) t (escolher-ui (achar-linha-ui :profile (second cmd)))))
    (:start (if (eq *tela-ui* :playing) t (pulso-ui 40 0)))
    (:walk
     (unless *y-ui*
       (setf *y-ui* (entity-y (personagem w)))
       (evento-tecla-teste 82 t)) ; UP físico agora é mover W.
     (when (> (- *y-ui* (entity-y (personagem w))) .3)
       (evento-tecla-teste 82 nil) (setf *teste-espera* 5) t))
    (:pause (if (eq *tela-ui* :pause) t (pulso-ui 44 6)))
    (:manual (if (probe-file (merge-pathnames "manual-001.save" (diretorio-saves))) t (escolher-ui 0)))
    (:overwrite
     (let ((p (merge-pathnames "manual-001.save" (diretorio-saves))))
       (cond ((null *fase-ui*)
              (setf *bytes-ui* (uiop:read-file-string p) *fase-ui* :open) nil)
             ((eq *fase-ui* :open)
              (if (eq *tela-ui* :confirm)
                  (progn (assert (zerop *indice-menu*))
                         (capture-renderer "build/player-ui-playtest/confirm.ppm")
                         (setf *fase-ui* :confirm) nil)
                  (escolher-ui (achar-linha-ui :save-file p))))
             ((eq *fase-ui* :confirm)
              (if (eq *tela-ui* :saves) (setf *fase-ui* :verify)
                  (escolher-ui (if (second cmd) 1 0))) nil)
             (t (assert (equal *bytes-ui* (uiop:read-file-string p)))
                ;; Mundo pausado: confirmação grava o mesmo estado e cria .bak.
                (when (second cmd) (assert (probe-file (pathname (format nil "~A.bak" p)))))
                (setf *fase-ui* nil) t))))
    (:finish
     (assert (eq *tela-ui* :playing))
     (assert (= 82 (codigo-fisico :keyboard 26)))
     (assert (= 3 (codigo-fisico :controller 0)))
     (assert (= 3 (codigo-fisico :mouse 1)))
     (assert (> (- *y-ui* (entity-y (personagem w))) .3))
     (assert (equal "profile-001" (ler-documento-ui (merge-pathnames "profiles/active-profile.sexp" (diretorio-saves)))))
     (validar-configuracoes (ler-documento-ui (caminho-perfil)))
     (format t "~&SDL PLAYER UI OK: capture, conflicts, remapped movement, profiles, save/overwrite/load~%")
     (stop-game) t)))

(defparameter *roteiro-ui*
  '((:menu :main-menu 2) (:setting 0 :pt) (:setting 3 (1600 900)) (:setting 5 9/10)
    (:menu :settings 12)
    (:bind :keyboard 26 82) (:bind :keyboard 40 14)
    (:bind :controller 0 3) (:bind :mouse 1 3) (:shot "controls") (:back)
    (:input-mode t) (:menu :settings 13) (:profile-new) (:profile "default")
    (:profile "profile-001") (:shot "profiles") (:back) (:back) (:start)
    (:walk) (:pause) (:menu :pause 1) (:manual) (:shot "saves")
    (:overwrite nil) (:overwrite t) (:back) (:menu :pause 3)
    (:menu :main-menu 1) (:menu :saves 0) (:finish)))
(preparar :safe-mode t) (aplicar-controles nil)
(setf *pular-menu-principal* nil *perfil-ativo* "default" *dificuldade-atual* :peaceful)
(ensure-directories-exist "build/player-ui-playtest/controls.ppm")
(run-game
 (define-game :title "Asterion player UI playtest" :start #'iniciar-mundo :input #'entrada :update #'atualizar
  :render (lambda (w alpha)
    (incf *teste-frame*) (renderizar w alpha)
    (when (= *teste-frame* 1)
      (let ((id (cffi:foreign-funcall "SDL_JoystickAttachVirtual" :int 1 :int 4 :int 15 :int 0 :int)))
        (assert (>= id 0)) (setf *teste-joystick* (cffi:foreign-funcall "SDL_JoystickOpen" :int id :pointer))))
    (when (> *teste-frame* 10)
      (cond (*teste-soltar* (funcall *teste-soltar*) (setf *teste-soltar* nil))
            ((plusp *teste-espera*) (decf *teste-espera*))
            (t (let ((cmd (nth *etapa-ui* *roteiro-ui*)))
                 (when (> (- *teste-frame* *teste-passo-frame*) 1600)
                   (error "UI stalled ~S: ~S ~S" cmd *tela-ui* *mensagem-menu*))
                 (when (executar-ui w cmd)
                   (incf *etapa-ui*) (setf *teste-passo-frame* *teste-frame*)
                   (format t "~&UI STEP ~D: ~S~%" *etapa-ui* cmd))))))))
 :world (new-game :difficulty :peaceful))
