(defpackage #:asterion-tests
  (:use #:cl #:antigonus)
  (:export #:run-all))
(in-package #:asterion-tests)

(defvar *executados* 0)
(defmacro verificar (condicao &optional (mensagem "verificação falhou"))
  `(progn (incf *executados*) (unless ,condicao (error "~A: ~S" ,mensagem ',condicao))))

(defun preparar () (asterion-assembly::preparar :safe-mode t))

(defun contar-item-transportador (predio item)
  (+ (inventory-count (building-inventory predio) item)
     (let ((pistas (getf (building-state predio) :belt-lanes)))
       (if pistas
           (loop for pista across pistas
                 sum (loop for i below (belt-lane-count pista)
                           when (eq item (aref (belt-lane-items pista) i))
                             sum (aref (belt-lane-stacks pista) i)))
           0))))

(defun teste-dsl-e-catalogo ()
  (preparar)
  (verificar (macro-function 'defitem) "DEFITEM deve ser macro")
  (verificar (macro-function 'defsystem) "DEFSYSTEM deve ser macro")
  (verificar (macro-function 'defanimation) "DEFANIMATION deve ser macro")
  (verificar (= 70 (hash-table-count antigonus::*itens*)))
  (verificar (= 90 (hash-table-count antigonus::*receitas*)))
  (verificar (= 52 (hash-table-count antigonus::*construcoes*)))
  (verificar (= 36 (hash-table-count antigonus::*tecnologias*)))
  (let ((indices (append (mapcar (lambda (p) (cons :v1 (cdr p)))
                                 asterion-assembly::*sprites-construcoes*)
                         (mapcar (lambda (p) (cons :v2 (cdr p)))
                                 asterion-assembly::*sprites-construcoes-v2*))))
    (verificar (= 52 (length indices)) "cada construção precisa de um sprite")
    (verificar (= 52 (length (remove-duplicates indices :test #'equal)))
               "sprites estáticos de construção não podem ser reutilizados"))
  (let ((indices (append (mapcar (lambda (p) (cons :v1 (cdr p)))
                                 asterion-assembly::*sprites-itens*)
                         (mapcar (lambda (p) (cons :v2 (cdr p)))
                                 asterion-assembly::*sprites-itens-v2*))))
    (verificar (= 70 (length indices)) "todo item precisa de ícone")
    (verificar (= 70 (length (remove-duplicates indices :test #'equal)))
               "ícones de itens não podem ser reutilizados")))

(defun teste-animacoes ()
  (reset-engine)
  (defanimation :test-loop :sheet :test :start 8 :frames 4 :fps 2)
  (defanimation :test-once :sheet :test :start 20 :frames 3 :fps 2 :loop nil)
  (verificar (= 8 (animation-frame :test-loop 0.0)))
  (verificar (= 11 (animation-frame :test-loop 1.5)))
  (verificar (= 8 (animation-frame :test-loop 2.0)) "animação deve fechar o loop")
  (verificar (= 22 (animation-frame :test-once 99.0)) "animação sem loop deve parar"))

(defun teste-transacao-inventario ()
  (let ((inv (make-hash-table :test #'equal)))
    (inventory-add inv :iron 10)
    (with-inventory-transaction (inv) (inventory-remove inv :iron 7) nil)
    (verificar (= 10 (inventory-count inv :iron)) "rollback do inventário")
    (with-inventory-transaction (inv) (inventory-remove inv :iron 4) t)
    (verificar (= 6 (inventory-count inv :iron)) "commit do inventário")))

(defun teste-determinismo ()
  (preparar)
  (let ((a (asterion-assembly:new-game :seed 4242 :difficulty :peaceful))
        (b (asterion-assembly:new-game :seed 4242 :difficulty :peaceful)))
    (dolist (w (list a b))
      (place-building w :miner -4 -4)
      (dotimes (i 450) (declare (ignore i)) (simulate-tick w)))
    (verificar (= (world-tick a) (world-tick b)))
    (verificar (= (world-pollution a) (world-pollution b)))
    (verificar (= (inventory-count (building-inventory (building-at a -4 -4)) :iron-ore)
                  (inventory-count (building-inventory (building-at b -4 -4)) :iron-ore)))))

(defun teste-producao-e-logistica ()
  (preparar)
  (let ((w (asterion-assembly:new-game :difficulty :peaceful)))
    (let ((forno (place-building w :stone-furnace 3 0 :recipe :smelt-iron)))
      (inventory-add (building-inventory forno) :iron-ore 2)
      (dotimes (i 50) (declare (ignore i)) (simulate-tick w))
      (verificar (= 1 (inventory-count (building-inventory forno) :iron-plate)))
      (verificar (= 1 (gethash :items-crafted (world-game-data w) 0))
                 "telemetria deve contar saídas realmente produzidas"))
    (let ((belt (place-building w :belt 1 0 :rotation 2)))
      (inventory-add (building-inventory belt) :iron-plate 1)
      (dotimes (i 8) (declare (ignore i)) (simulate-tick w))
      (verificar (> (inventory-count (asterion-assembly::inventario-jogador w) :iron-plate) 120)))))

(defun teste-item-no-braco ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :difficulty :peaceful))
         (origem (place-building w :stone-furnace 10 10))
         (braco (place-building w :inserter 11 10 :rotation 0))
         (destino (place-building w :belt 12 10)))
    (inventory-add (building-inventory origem) :iron-plate 1)
    (dotimes (i 8) (declare (ignore i)) (simulate-tick w))
    (verificar (eq :iron-plate (getf (building-state braco) :carried-item))
               "braço deve registrar visualmente o item transferido")
    (verificar (= 1 (contar-item-transportador destino :iron-plate)))
    (verificar (plusp (gethash :items-moved (world-game-data w) 0))
               "telemetria deve contar itens transferidos")))

(defun teste-feedback-da-fabrica ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :difficulty :peaceful))
         (minerador (place-building w :miner -5 -4))
         (saida-minerador (place-building w :belt -4 -4 :rotation 0))
         (continuidade (place-building w :belt -3 -4 :rotation 0))
         (ponta (place-building w :belt 7 7 :rotation 0)))
    (inventory-add (building-inventory ponta) :iron-ore 1)
    (dotimes (i 45) (declare (ignore i)) (simulate-tick w))
    (asterion-assembly::atualizar-alertas-fabrica w)
    (verificar (eq :blocked (asterion-assembly::estado-predio w ponta))
               "inspetor deve explicar uma saída de esteira bloqueada")
    (verificar (eq :working (asterion-assembly::estado-predio w minerador))
               "minerador alimentado sobre recurso deve aparecer operando")
    (verificar (plusp (gethash :items-mined (world-game-data w) 0))
               "telemetria deve contar recursos minerados")
    (verificar (plusp (+ (contar-item-transportador saida-minerador :iron-ore)
                         (contar-item-transportador continuidade :iron-ore)))
               "minerador deve descarregar diretamente na esteira frontal")
    (verificar (= 1 (gethash :blocked-output-count (world-game-data w) 0))
               "alerta deve resumir saídas bloqueadas")))

(defun teste-energia-sem-piscar ()
  "Três mineradores com esteiras não podem alternar ENABLED a cada tick."
  (preparar)
  (let ((w (asterion-assembly:new-game :difficulty :peaceful))
        (consumidores nil)
        (estavel t))
    (dolist (y '(-2 0 2))
      (push (place-building w :miner -5 y) consumidores)
      (push (place-building w :belt -4 y :rotation 0) consumidores))
    (dotimes (i 12)
      (declare (ignore i))
      (simulate-tick w)
      (unless (every (lambda (b)
                       (and (building-enabled b)
                            (getf (building-state b) :powered)))
                     consumidores)
        (setf estavel nil)))
    (verificar estavel "a rede inicial não deve alternar construções entre ligada e desligada")
    (verificar (= 50 (gethash :power-produced (world-game-data w)))
               "o núcleo inicial deve fornecer 50 MW")
    (verificar (= 21 (gethash :power-used (world-game-data w)))
               "a demanda deve incluir três mineradores e três esteiras")
    ;; Mesmo uma sobrecarga real deve produzir um conjunto estável de cargas
    ;; alimentadas, nunca a alternância clara/escura que causava o flicker.
    (dotimes (i 5)
      (push (place-building w :miner (+ 4 i) 4) consumidores))
    (simulate-tick w)
    (let ((estado (mapcar (lambda (b) (getf (building-state b) :powered)) consumidores))
          (sobrecarga-estavel t))
      (dotimes (i 12)
        (declare (ignore i))
        (simulate-tick w)
        (unless (equal estado
                       (mapcar (lambda (b) (getf (building-state b) :powered))
                               consumidores))
          (setf sobrecarga-estavel nil)))
      (verificar (member nil estado) "a sobrecarga deve deixar alguma carga sem energia")
      (verificar sobrecarga-estavel "a distribuição em sobrecarga deve permanecer estável")
      (verificar (every #'building-enabled consumidores)
                 "brownout não deve alterar a opção ENABLED das construções"))))

(defun teste-divisor-logistico ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :difficulty :peaceful))
         (divisor (place-building w :splitter 10 10 :rotation 0))
         (frente (place-building w :belt 11 10 :rotation 0))
         (ramal (place-building w :belt 10 11 :rotation 1)))
    (inventory-add (building-inventory divisor) :iron-ore 4)
    (dotimes (i 32) (declare (ignore i)) (simulate-tick w))
    (verificar (= 2 (contar-item-transportador frente :iron-ore))
               "divisor deve alimentar a saída frontal")
    (verificar (= 2 (contar-item-transportador ramal :iron-ore))
               "divisor deve alternar de forma justa para o ramal")
    (verificar (= 0 (getf (building-state divisor) :next-output))
               "quatro transferências devem completar o ciclo determinístico")))

(defun teste-arrasto-e-desfazer ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :difficulty :peaceful))
         (inventario (asterion-assembly::inventario-jogador w))
         (ferro-inicial (inventory-count inventario :iron-plate)))
    (setf asterion-assembly::*indice-selecao* 0
          asterion-assembly::*rotacao-construcao* 0)
    (verificar (= 0 (asterion-assembly::rotacao-entre-celulas '(2 . 2) '(3 . 2))))
    (verificar (= 1 (asterion-assembly::rotacao-entre-celulas '(2 . 2) '(2 . 3))))
    (asterion-assembly::construir-na-celula w 2 2)
    (asterion-assembly::construir-na-celula w 3 2)
    (verificar (= (- ferro-inicial 2) (inventory-count inventario :iron-plate))
               "linha construída deve consumir cada segmento")
    (verificar (building-at w 3 2))
    (asterion-assembly::desfazer-ultima-construcao w)
    (verificar (null (building-at w 3 2)) "undo deve remover somente o segmento mais recente")
    (verificar (building-at w 2 2) "undo deve preservar segmentos anteriores")
    (verificar (= (1- ferro-inicial) (inventory-count inventario :iron-plate))
               "undo recente deve devolver o custo integral")))

(defun contar-entidades (mundo predicado)
  (let ((quantidade 0))
    (map-entities (lambda (e) (when (funcall predicado e) (incf quantidade))) mundo)
    quantidade))

(defun teste-protagonista-ecossistema-e-vfx ()
  (preparar)
  (let ((w (asterion-assembly:new-game :seed 77 :difficulty :peaceful)))
    (verificar (= 1 (contar-entidades w (lambda (e) (eq (entity-kind e) :engineer))))
               "deve existir um protagonista humanoide")
    (verificar (= 0 (contar-entidades w (lambda (e) (eq (entity-kind e) :commander-drone))))
               "o drone não pode continuar como protagonista")
    (verificar (= 24 (contar-entidades
                      w (lambda (e) (member (entity-kind e)
                                            asterion-assembly::*fauna-passiva*))))
               "o mundo deve nascer com fauna passiva")
    ;; A atlas foi desenhada em oito vistas. Estes pontos cardeais impedem que
    ;; uma regressão volte a girar o corpo 3/4 de cabeça para baixo ou ao lado
    ;; oposto ao deslocamento.
    (let ((engenheiro nil))
      (map-entities (lambda (e)
                      (when (eq (entity-kind e) :engineer)
                        (setf engenheiro e)))
                    w)
      (dolist (caso `((0.0 6 :leste)
                      (,(coerce (/ pi 2) 'single-float) 0 :sul)
                      (,(- (coerce (/ pi 2) 'single-float)) 4 :norte)
                      (,(coerce pi 'single-float) 2 :oeste)))
        (setf (getf (entity-data engenheiro) :heading) (first caso))
        (verificar (= (second caso)
                      (asterion-assembly::indice-direcional-engenheiro engenheiro))
                   (format nil "vista do engenheiro deve apontar para ~A" (third caso)))))
    (let ((efeito (asterion-assembly::criar-efeito w :vfx-spark 2 2 :duracao 2)))
      (asterion-assembly::sistema-efeitos w)
      (verificar (= 1 (getf (entity-data efeito) :age)) "VFX deve avançar por tick")
      (asterion-assembly::sistema-efeitos w)
      (verificar (= 0 (contar-entidades w (lambda (e) (eq (entity-kind e) :vfx-spark))))
                 "VFX temporário deve ser removido"))))

(defun teste-arvore-tecnologica ()
  (preparar)
  (let ((w (asterion-assembly:new-game :difficulty :peaceful)))
    (verificar (asterion-assembly::tecnologia-disponivel-p w :automation))
    (verificar (not (asterion-assembly::tecnologia-disponivel-p w :logistics))
               "pré-requisito deve bloquear o ramo")
    (verificar (not (asterion-assembly::construcao-desbloqueada-p w :assembler)))
    (place-building w :laboratory 3 3)
    (setf (gethash :research-progress (world-game-data w)) 19)
    (inventory-add (asterion-assembly::inventario-jogador w) :science-red 1)
    (dotimes (i 60) (declare (ignore i)) (simulate-tick w))
    (verificar (member :automation (world-research w)) "pesquisa ativa deve concluir")
    (verificar (asterion-assembly::construcao-desbloqueada-p w :assembler)
               "pesquisa deve liberar a construção")))

(defun teste-save-roundtrip ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :seed 999 :difficulty :explorer))
         (arquivo (merge-pathnames "asterion-test.save" (uiop:temporary-directory))))
    (place-building w :rail 7 9)
    (dotimes (i 31) (declare (ignore i)) (simulate-tick w))
    (unwind-protect
         (progn (save-game w arquivo)
                (let ((texto (uiop:read-file-string arquivo)))
                  (verificar (null (search "#." texto))
                             "save não pode conter avaliação de leitor"))
                (let ((r (load-game arquivo)))
                  (verificar (= 999 (world-seed r)))
                  (verificar (= 31 (world-tick r)))
                  (verificar (eq :rail (building-kind (building-at r 7 9))))
                  (verificar (= 120 (inventory-count
                                     (asterion-assembly::inventario-jogador r)
                                     :iron-plate)))))
      (when (probe-file arquivo) (delete-file arquivo)))))

(defun teste-pathfinding-e-trilhos ()
  (preparar)
  (let ((caminho (find-path '(0 . 0) '(4 . 0)
                            (lambda (p) (equal p '(2 . 0))))))
    (verificar (equal '(0 . 0) (first caminho)))
    (verificar (equal '(4 . 0) (car (last caminho))))
    (verificar (not (member '(2 . 0) caminho :test #'equal)))))

(defun teste-mod ()
  (preparar)
  (let* ((raiz (uiop:pathname-directory-pathname
                (asdf:system-source-file :asterion-assembly)))
         (mods (discover-mods (merge-pathnames "mods/" raiz))))
    (verificar (= 1 (length mods)))
    (load-mods mods)
    (verificar (find-item :luminous-bearing))
    (verificar (> (length (mod-fingerprint)) 0))))

(defun teste-desempenho-basico ()
  (preparar)
  (let ((w (asterion-assembly:new-game :difficulty :peaceful)))
    (loop for x from 1 to 50 do
      (loop for y from 1 to 40 do (place-building w :belt x y)))
    (let ((inicio (get-internal-real-time)))
      (dotimes (i 30) (declare (ignore i)) (simulate-tick w))
      (let ((segundos (/ (- (get-internal-real-time) inicio)
                         internal-time-units-per-second)))
        (verificar (< segundos 5.0) "2.000 construções devem simular 30 ticks em menos de 5 s")))))

(defun teste-fundacao-2-0 ()
  (preparar)
  (verificar (string= "2.0.0" +engine-version+))
  (verificar (= 2 +save-version+))
  (let ((w (make-world :seed 81 :worker-count 4)))
    (set-world-tile w -1 -33 17)
    (verificar (= 17 (world-tile w -1 -33)) "tile deve sobreviver em chunk negativo")
    (verificar (= -1 (chunk-x (find-chunk w -1 -33))))
    (verificar (= -2 (chunk-y (find-chunk w -1 -33))))
    (set-chunk-resource-count w 3 4 :iron-ore 12)
    (verificar (= 5 (deplete-resource w 3 4 :iron-ore 5)))
    (verificar (= 7 (chunk-resource-count w 3 4 :iron-ore)))
    (let ((resultados (run-deterministic-jobs '(5 4 3 2 1)
                                               (lambda (valor indice)
                                                 (+ valor indice))
                                               :workers 4)))
      (verificar (equal '(5 5 5 5 5) resultados)
                 "jobs devem retornar na ordem de entrada"))))

(defun teste-pistas-fluidos-energia-e-circuitos-2-0 ()
  (let ((pista (make-belt-lane :capacity 4)))
    (verificar (belt-lane-insert pista :iron :position 0))
    (verificar (belt-lane-insert pista :copper :position 5000))
    (advance-belt-lane pista 65535)
    (multiple-value-bind (item pilha pronto) (belt-lane-remove-front pista)
      (verificar pronto) (verificar (eq :copper item)) (verificar (= 1 pilha)))
    (verificar (= 1 (belt-lane-count pista))))
  (let ((fluido (make-fluid-network :id 1 :fluid :water :capacity 100.0)))
    (simulate-fluid-network fluido :inflow 60.0)
    (verificar (= 60.0 (fluid-network-volume fluido)))
    (verificar (= 0.6 (fluid-network-pressure fluido))))
  (let ((rede (make-circuit-network :id 1)))
    (circuit-write rede :iron 4)
    (circuit-write rede :iron 3 :mode :add)
    (verificar (= 7 (circuit-read rede :iron))))
  (let ((energia (make-power-network :id 1 :generation 10.0))
        (estado (make-array 2 :initial-element nil)))
    (allocate-power-network
     energia (list (list 2 0 6.0 (lambda (x) (setf (aref estado 1) x)))
                   (list 1 10 6.0 (lambda (x) (setf (aref estado 0) x)))))
    (verificar (aref estado 0) "carga prioritária deve receber energia")
    (verificar (null (aref estado 1)) "carga secundária deve permanecer estável em brownout")))

(defun teste-ferrovia-e-plantas-2-0 ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :difficulty :peaceful))
         (grafo (world-rail-graph w))
         (a (add-rail-node grafo 0 0))
         (b (add-rail-node grafo 1 1))
         (aresta (add-rail-edge grafo a b :geometry :diagonal :block 7)))
    (declare (ignore aresta))
    (verificar (reserve-rail-block grafo 7 10))
    (verificar (null (reserve-rail-block grafo 7 11)))
    (verificar (= 1 (release-rail-blocks grafo 10)))
    (verificar (equal '((1 2)) (rail-deadlocks '((1 . 2) (2 . 1)))))
    (place-building w :belt 8 9 :rotation 1)
    (let ((planta (capture-blueprint w 8 9 8 9 :id :test)))
      (verificar (= 1 (length (blueprint-definition-entries planta))))
      (verificar (= 1 (length (apply-blueprint w planta 12 12))))
      (verificar (= 1 (length (world-ghosts w)))))))

(defun teste-integracao-asterion-2-0 ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :difficulty :peaceful))
         (recurso (asterion-assembly::recurso-em w -5 -4))
         (antes (chunk-resource-count w -5 -4 recurso)))
    (deplete-resource w -5 -4 recurso 7)
    (verificar (= (- antes 7) (chunk-resource-count w -5 -4 recurso))
               "jazida materializada não pode renascer após extração")
    (let ((a (place-building w :pipe 10 10))
          (b (place-building w :pipe 11 10)))
      (inventory-add (building-inventory a) :water 40)
      (simulate-tick w)
      (let ((rede (gethash (getf (building-state a) :fluid-network)
                           (world-fluid-networks w))))
        (verificar (= 40.0 (fluid-network-volume rede)))
        (verificar (> (fluid-network-pressure rede) 0.0)))
      (inventory-add (building-inventory b) :oil 1)
      (simulate-tick w)
      (verificar (getf (building-state b) :fluid-conflict)
                 "rede deve bloquear mistura de fluidos"))
    (place-building w :circuit-sensor 15 15)
    (place-building w :arithmetic-combinator 16 15
                    :state '(:input-signal :items-moved :output-signal :halved
                             :operand 2))
    (setf (gethash :items-moved (world-game-data w)) 9)
    (simulate-tick w)
    (verificar (= 4 (circuit-read (gethash 0 (world-circuit-networks w)) :halved)))
    (let ((belt (place-building w :belt 20 20)))
      (inventory-add (building-inventory belt) :iron-ore 3)
      (dotimes (i 3) (declare (ignore i)) (simulate-tick w))
      (let ((arquivo #P"/tmp/asterion-v2-lanes.sexp"))
        (unwind-protect
             (progn
               (save-game w arquivo)
               (let* ((carregado (load-game arquivo))
                      (restaurado (building-at carregado 20 20))
                      (pistas (getf (building-state restaurado) :belt-lanes)))
                 (verificar (= 2 (length pistas)))
                 (verificar (= 3 (loop for pista across pistas
                                       sum (belt-lane-count pista))))))
          (when (probe-file arquivo) (delete-file arquivo)))))))

(defun teste-logistica-especializada-2-0 ()
  (preparar)
  (let ((w (asterion-assembly:new-game :difficulty :peaceful)))
    (let ((entrada (place-building w :underground-belt 30 30 :rotation 0))
          (saida (place-building w :underground-belt 34 30 :rotation 0))
          (destino (place-building w :belt 35 30 :rotation 0)))
      (declare (ignore saida))
      (inventory-add (building-inventory entrada) :iron-ore 1)
      (dotimes (i 9) (declare (ignore i)) (simulate-tick w))
      (verificar (= 1 (contar-item-transportador destino :iron-ore))
                 "esteira subterrânea deve atravessar até cinco células"))
    (let ((divisor (place-building w :filter-splitter 40 40 :rotation 0
                                  :state '(:filter :iron-ore)))
          (ferro (place-building w :belt 41 40 :rotation 0))
          (cobre (place-building w :belt 40 41 :rotation 1)))
      (inventory-add (building-inventory divisor) :iron-ore 1)
      (inventory-add (building-inventory divisor) :copper-ore 1)
      (dotimes (i 10) (declare (ignore i)) (simulate-tick w))
      (verificar (= 1 (contar-item-transportador ferro :iron-ore)))
      (verificar (= 1 (contar-item-transportador cobre :copper-ore))))
    (let ((origem (place-building w :stone-furnace 50 50))
          (braco (place-building w :stack-inserter 51 50 :rotation 0))
          (destino (place-building w :stone-furnace 52 50)))
      (declare (ignore braco))
      (inventory-add (building-inventory origem) :gear 4)
      (dotimes (i 8) (declare (ignore i)) (simulate-tick w))
      (verificar (= 4 (inventory-count (building-inventory destino) :gear))
                 "braço empilhador deve transferir quatro itens por ciclo"))))

(defun run-all ()
  (setf *executados* 0)
  (dolist (teste '(teste-dsl-e-catalogo teste-animacoes
                    teste-transacao-inventario teste-determinismo
                    teste-producao-e-logistica teste-item-no-braco
                    teste-feedback-da-fabrica teste-energia-sem-piscar teste-save-roundtrip
                    teste-protagonista-ecossistema-e-vfx teste-arvore-tecnologica
                    teste-divisor-logistico teste-arrasto-e-desfazer
                    teste-pathfinding-e-trilhos teste-mod teste-desempenho-basico
                    teste-fundacao-2-0
                    teste-pistas-fluidos-energia-e-circuitos-2-0
                    teste-ferrovia-e-plantas-2-0 teste-integracao-asterion-2-0
                    teste-logistica-especializada-2-0))
    (format t "~&[TEST] ~A~%" teste) (funcall teste))
  (format t "~&OK — ~D verificações concluídas.~%" *executados*) t)
