;;;; Jornada industrial executada com simulação real, sem falsificar provas de trabalho.
(in-package #:asterion-tests)

(defun avancar-ate (mundo capitulo)
  (loop repeat 900 until (>= (gethash :chapter (world-game-data mundo)) capitulo)
        do (simulate-tick mundo))
  (verificar (= capitulo (gethash :chapter (world-game-data mundo)))
             "a configuração funcional deve concluir o desafio sustentado"))

(defun teste-tutorial-circuitos ()
  (dolist (dificuldade '(:peaceful :explorer :standard :hostile))
    (preparar)
    (let ((w (asterion-assembly:new-game :difficulty dificuldade)))
      (setf (world-pollution w) 1000.0)
      (place-building w :miner -4 -4)
      (dotimes (i 240) (simulate-tick w))
      (verificar (= 1 (gethash :chapter (world-game-data w))) "minerador sem transporte não basta")
      (place-building w :belt -3 -4)
      (place-building w :logistic-chest -2 -4)
      (avancar-ate w 2)
      (let ((forno (place-building w :stone-furnace -2 -2)))
        (inventory-add (building-inventory forno) :iron-ore 40)
        (dotimes (i 240) (simulate-tick w))
        (verificar (= 2 (gethash :chapter (world-game-data w))) "núcleo sozinho não prova geração adicional")
        (place-building w :solar-panel 3 3)
        (avancar-ate w 3))
      (let* ((sensor (place-building w :circuit-sensor -6 2))
             (origem (place-building w :logistic-chest -5 2))
             (braco (place-building w :inserter -4 2)))
        (place-building w :logistic-chest -3 2)
        (inventory-add (building-inventory origem) :iron-plate 10)
        (connect-circuit w sensor braco)
        (configure-circuit-device braco
          (make-circuit-device-config :behavior :actuator :input-signal nil
            :condition (make-circuit-condition :left '(:virtual :wrong) :comparator :> :constant 2)))
        (dotimes (i 240) (simulate-tick w))
        (verificar (= 3 (gethash :chapter (world-game-data w))) "sinal errado não controla estoque")
        (configure-circuit-device braco
          (make-circuit-device-config :behavior :actuator :input-signal nil
            :condition (make-circuit-condition :left '(:item :iron-plate) :comparator :> :constant 2)))
        (avancar-ate w 4)
        (verificar (= 2 (inventory-count (building-inventory origem) :iron-plate))))
      (let ((sensor (place-building w :circuit-sensor 8 0))
            (divisor (place-building w :splitter 10 0)))
        (place-building w :belt 11 0) (place-building w :belt 10 1 :rotation 1)
        (place-building w :logistic-chest 12 0) (place-building w :logistic-chest 10 2)
        (connect-circuit w sensor divisor)
        (configure-circuit-device divisor
          (make-circuit-device-config :behavior :actuator :input-signal '(:item :iron-ore)))
        (inventory-add (building-inventory divisor) :iron-ore 4)
        (dotimes (i 240) (simulate-tick w))
        (verificar (= 4 (gethash :chapter (world-game-data w))) "uma só saída não prova filtragem")
        (inventory-add (building-inventory divisor) :copper-ore 4)
        (avancar-ate w 5))
      (let* ((origem (place-building w :tank 20 0))
             (bomba (place-building w :pump 21 0))
             (destino (place-building w :tank 22 0))
             (sensor (place-building w :circuit-sensor 22 -1 :rotation 1
                                    :state '(:sensor-mode :fluid))))
        (inventory-add (building-inventory origem) :water 600)
        (configure-circuit-device sensor
          (make-circuit-device-config :behavior :sensor :output-signal '(:fluid :water)))
        (configure-circuit-device bomba
          (make-circuit-device-config :behavior :actuator :input-signal nil
            :condition (make-circuit-condition :left '(:fluid :water) :comparator :< :constant 100)))
        (connect-circuit w sensor bomba)
        (avancar-ate w 6)
        (verificar (= 600 (+ (getf (building-state origem) :fluid-volume)
                             (getf (building-state destino) :fluid-volume))) "bomba conserva água")
        (verificar (<= 100 (getf (building-state destino) :fluid-volume) 116))
        (verificar (not (getf (building-state bomba) :circuit-enabled))))
      (let ((contador (place-building w :arithmetic-combinator 30 0))
            (lampada (place-building w :signal-lamp 32 0))
            (alarme (place-building w :programmable-alarm 34 0)))
        (configure-circuit-device contador
          (make-circuit-device-config :behavior :arithmetic :input-signal '(:virtual :signal-a)
            :output-signal '(:virtual :signal-a) :operator :+ :constant 1))
        (dolist (b (list lampada alarme))
          (configure-circuit-device b
            (make-circuit-device-config :behavior :actuator
              :condition (make-circuit-condition :left '(:virtual :signal-a) :comparator :> :constant 5)))
          (connect-circuit w contador b :port-a :output))
        (dotimes (i 240) (simulate-tick w))
        (verificar (= 6 (gethash :chapter (world-game-data w))) "sem feedback não é um contador")
        (let ((hostis 0))
          (map-entities (lambda (e) (when (member (entity-kind e) asterion-assembly::*tipos-hostis*)
                                      (incf hostis))) w)
          (verificar (zerop hostis) "tutorial não deve gerar ataques em nenhuma dificuldade"))
        (connect-circuit w contador contador :port-a :output :port-b :input)
        (avancar-ate w 7)
        (verificar (getf (building-state lampada) :lamp-active))
        (verificar (getf (building-state alarme) :alarm-active))))))

(defun teste-gamepad-circuitos ()
  (preparar)
  (let* ((w (asterion-assembly:new-game :difficulty :peaceful))
         (a (place-building w :circuit-sensor -2 -1))
         (b (place-building w :signal-lamp 1 -1))
         (inv (asterion-assembly::inventario-jogador w))
         (antes (inventory-count inv :wire-red)))
    (set-camera 0 0 1.0)
    (setf asterion-assembly::*tela-ui* :playing asterion-assembly::*modo-circuito* nil
          asterion-assembly::*cor-fio-circuito* :red)
    (asterion-assembly::entrada w :controller-down 3)
    (verificar asterion-assembly::*modo-circuito*)
    (dolist (p (list a b))
      (multiple-value-bind (x y) (world-to-screen
                                  (asterion-assembly::posicao-porta-x p :main)
                                  (asterion-assembly::posicao-porta-y p))
        (setf asterion-assembly::*cursor-gamepad-x* x asterion-assembly::*cursor-gamepad-y* y)
        (asterion-assembly::entrada w :controller-down 0)))
    (verificar (= 1 (length (circuit-connections w))))
    (verificar (= (1- antes) (inventory-count inv :wire-red)))
    (asterion-assembly::entrada w :controller-down 13)
    (verificar (= antes (inventory-count inv :wire-red)))
    (asterion-assembly::entrada w :controller-down 2)
    (verificar (eq :green asterion-assembly::*cor-fio-circuito*))
    (asterion-assembly::entrada w :controller-axis 2 20000)
    (let ((x asterion-assembly::*cursor-gamepad-x*))
      (asterion-assembly::atualizar w (/ 1.0 30))
      (verificar (> asterion-assembly::*cursor-gamepad-x* x)))
    (asterion-assembly::entrada w :controller-disconnected)
    (verificar (every #'zerop asterion-assembly::*eixos-gamepad*))
    (setf asterion-assembly::*modo-circuito* nil)))
